// PandaFlip Word Bank - Comprehensive Chinese vocabulary
// Each word: { c: chinese, p: pinyin, e: english, i: icon (optional) }
// Levels 1-8, ~2000+ words

const WORD_BANK = {
  1: [
    {c:"一",p:"yī",e:"One",i:"keycap-1"},{c:"二",p:"èr",e:"Two",i:"victory-hand"},
    {c:"三",p:"sān",e:"Three",i:"keycap-3"},{c:"四",p:"sì",e:"Four"},
    {c:"五",p:"wǔ",e:"Five",i:"raised-hand"},{c:"六",p:"liù",e:"Six",i:"game-die"},
    {c:"七",p:"qī",e:"Seven"},{c:"八",p:"bā",e:"Eight"},
    {c:"九",p:"jiǔ",e:"Nine"},{c:"十",p:"shí",e:"Ten"},
    {c:"人",p:"rén",e:"Person",i:"person-standing"},{c:"大",p:"dà",e:"Big",i:"elephant"},
    {c:"小",p:"xiǎo",e:"Small",i:"ant"},{c:"口",p:"kǒu",e:"Mouth",i:"mouth"},
    {c:"手",p:"shǒu",e:"Hand",i:"waving-hand"},{c:"山",p:"shān",e:"Mountain",i:"mountain"},
    {c:"水",p:"shuǐ",e:"Water",i:"droplet"},{c:"火",p:"huǒ",e:"Fire",i:"fire"},
    {c:"天",p:"tiān",e:"Sky",i:"sun-behind-cloud"},{c:"日",p:"rì",e:"Day",i:"sun"},
    {c:"月",p:"yuè",e:"Moon",i:"crescent-moon"},{c:"木",p:"mù",e:"Wood"},
    {c:"土",p:"tǔ",e:"Earth"},{c:"石",p:"shí",e:"Stone"},
    {c:"田",p:"tián",e:"Field"},{c:"目",p:"mù",e:"Eye",i:"eyes"},
    {c:"耳",p:"ěr",e:"Ear",i:"ear"},{c:"心",p:"xīn",e:"Heart",i:"red-heart"},
    {c:"门",p:"mén",e:"Door"},{c:"雨",p:"yǔ",e:"Rain",i:"cloud-with-rain"},
    {c:"上",p:"shàng",e:"Up"},{c:"下",p:"xià",e:"Down"},
    {c:"中",p:"zhōng",e:"Middle"},{c:"头",p:"tóu",e:"Head"},
    {c:"足",p:"zú",e:"Foot"},{c:"女",p:"nǚ",e:"Woman"},
    {c:"男",p:"nán",e:"Man"},{c:"子",p:"zǐ",e:"Child"},
    {c:"王",p:"wáng",e:"King"},{c:"力",p:"lì",e:"Power/Strength"},
    {c:"刀",p:"dāo",e:"Knife"},{c:"牙",p:"yá",e:"Tooth"},
    {c:"毛",p:"máo",e:"Hair/Fur"},{c:"气",p:"qì",e:"Air/Qi"},
    {c:"车",p:"chē",e:"Car/Vehicle"},{c:"飞",p:"fēi",e:"Fly"},
    {c:"东",p:"dōng",e:"East"},{c:"西",p:"xī",e:"West"},
    {c:"南",p:"nán",e:"South"},{c:"北",p:"běi",e:"North"},
    {c:"出",p:"chū",e:"Go out"},{c:"入",p:"rù",e:"Enter"},
    {c:"开",p:"kāi",e:"Open"},{c:"关",p:"guān",e:"Close"},
    {c:"正",p:"zhèng",e:"Correct"},{c:"反",p:"fǎn",e:"Opposite"},
    {c:"长",p:"cháng",e:"Long"},{c:"方",p:"fāng",e:"Square"},
    {c:"半",p:"bàn",e:"Half"},{c:"回",p:"huí",e:"Return"},
    {c:"米",p:"mǐ",e:"Rice"},{c:"果",p:"guǒ",e:"Fruit"},
  ],
  2: [
    {c:"猫",p:"māo",e:"Cat",i:"cat-face"},{c:"狗",p:"gǒu",e:"Dog",i:"dog-face"},
    {c:"鱼",p:"yú",e:"Fish",i:"fish"},{c:"鸟",p:"niǎo",e:"Bird",i:"bird"},
    {c:"马",p:"mǎ",e:"Horse",i:"horse-face"},{c:"牛",p:"niú",e:"Cow",i:"cow-face"},
    {c:"羊",p:"yáng",e:"Sheep"},{c:"猪",p:"zhū",e:"Pig",i:"pig-face"},
    {c:"兔",p:"tù",e:"Rabbit",i:"rabbit-face"},{c:"虎",p:"hǔ",e:"Tiger",i:"tiger-face"},
    {c:"龙",p:"lóng",e:"Dragon",i:"dragon"},{c:"蛇",p:"shé",e:"Snake",i:"snake"},
    {c:"鸡",p:"jī",e:"Chicken",i:"rooster"},{c:"鸭",p:"yā",e:"Duck"},
    {c:"鹅",p:"é",e:"Goose"},{c:"虫",p:"chóng",e:"Bug",i:"bug"},
    {c:"红",p:"hóng",e:"Red",i:"red-heart"},{c:"蓝",p:"lán",e:"Blue",i:"blue-heart"},
    {c:"白",p:"bái",e:"White"},{c:"黑",p:"hēi",e:"Black"},
    {c:"绿",p:"lǜ",e:"Green",i:"green-heart"},{c:"黄",p:"huáng",e:"Yellow",i:"yellow-heart"},
    {c:"花",p:"huā",e:"Flower",i:"cherry-blossom"},{c:"树",p:"shù",e:"Tree",i:"deciduous-tree"},
    {c:"草",p:"cǎo",e:"Grass"},{c:"河",p:"hé",e:"River"},
    {c:"海",p:"hǎi",e:"Sea"},{c:"湖",p:"hú",e:"Lake"},
    {c:"风",p:"fēng",e:"Wind",i:"wind-face"},{c:"雪",p:"xuě",e:"Snow",i:"snowflake"},
    {c:"云",p:"yún",e:"Cloud",i:"cloud"},{c:"星",p:"xīng",e:"Star",i:"glowing-star"},
    {c:"冰",p:"bīng",e:"Ice"},{c:"竹",p:"zhú",e:"Bamboo"},
    {c:"金",p:"jīn",e:"Gold"},{c:"银",p:"yín",e:"Silver"},
    {c:"铁",p:"tiě",e:"Iron"},{c:"沙",p:"shā",e:"Sand"},
    {c:"岛",p:"dǎo",e:"Island"},{c:"森林",p:"sēn lín",e:"Forest"},
    {c:"紫",p:"zǐ",e:"Purple"},{c:"粉",p:"fěn",e:"Pink"},
    {c:"灰",p:"huī",e:"Gray"},{c:"棕",p:"zōng",e:"Brown"},
    {c:"橙",p:"chéng",e:"Orange (color)"},
    {c:"蝉",p:"chán",e:"Cicada"},{c:"蚊子",p:"wén zi",e:"Mosquito"},
    {c:"苍蝇",p:"cāng ying",e:"Fly (insect)"},{c:"瓢虫",p:"piáo chóng",e:"Ladybug"},
    {c:"蜗牛",p:"wō niú",e:"Snail"},{c:"螃蟹",p:"páng xiè",e:"Crab",i:"crab"},
    {c:"章鱼",p:"zhāng yú",e:"Octopus",i:"octopus"},
    {c:"鲸鱼",p:"jīng yú",e:"Whale",i:"whale"},
    {c:"熊",p:"xióng",e:"Bear",i:"bear"},{c:"狼",p:"láng",e:"Wolf"},
    {c:"狐狸",p:"hú li",e:"Fox",i:"fox"},{c:"松鼠",p:"sōng shǔ",e:"Squirrel"},
    {c:"刺猬",p:"cì wei",e:"Hedgehog"},{c:"骆驼",p:"luò tuo",e:"Camel"},
    {c:"斑马",p:"bān mǎ",e:"Zebra",i:"zebra"},
    {c:"袋鼠",p:"dài shǔ",e:"Kangaroo",i:"kangaroo"},
    {c:"考拉",p:"kǎo lā",e:"Koala"},{c:"鹦鹉",p:"yīng wǔ",e:"Parrot",i:"parrot"},
    {c:"猫头鹰",p:"māo tóu yīng",e:"Owl",i:"owl"},
    {c:"鸽子",p:"gē zi",e:"Pigeon"},{c:"老鹰",p:"lǎo yīng",e:"Eagle",i:"eagle"},
    {c:"天鹅",p:"tiān é",e:"Swan",i:"swan"},
    {c:"玫瑰",p:"méi gui",e:"Rose",i:"rose"},
    {c:"向日葵",p:"xiàng rì kuí",e:"Sunflower",i:"sunflower"},
    {c:"菊花",p:"jú huā",e:"Chrysanthemum"},{c:"荷花",p:"hé huā",e:"Lotus"},
    {c:"梅花",p:"méi huā",e:"Plum blossom"},{c:"松树",p:"sōng shù",e:"Pine tree",i:"evergreen-tree"},
    {c:"柳树",p:"liǔ shù",e:"Willow"},{c:"叶子",p:"yè zi",e:"Leaf",i:"fallen-leaf"},
    {c:"种子",p:"zhǒng zi",e:"Seed",i:"seedling"},{c:"根",p:"gēn",e:"Root"},
  ],
  3: [
    {c:"你好",p:"nǐ hǎo",e:"Hello",i:"waving-hand"},
    {c:"谢谢",p:"xiè xie",e:"Thank you",i:"folded-hands"},
    {c:"再见",p:"zài jiàn",e:"Goodbye"},{c:"对不起",p:"duì bu qǐ",e:"Sorry"},
    {c:"没关系",p:"méi guān xi",e:"It's okay"},{c:"请",p:"qǐng",e:"Please"},
    {c:"不客气",p:"bú kè qì",e:"You're welcome"},
    {c:"妈妈",p:"mā ma",e:"Mom",i:"woman"},{c:"爸爸",p:"bà ba",e:"Dad",i:"man"},
    {c:"哥哥",p:"gē ge",e:"Older brother"},{c:"姐姐",p:"jiě jie",e:"Older sister"},
    {c:"弟弟",p:"dì di",e:"Younger brother"},{c:"妹妹",p:"mèi mei",e:"Younger sister"},
    {c:"爷爷",p:"yé ye",e:"Grandpa (paternal)"},{c:"奶奶",p:"nǎi nai",e:"Grandma (paternal)"},
    {c:"外公",p:"wài gōng",e:"Grandpa (maternal)"},{c:"外婆",p:"wài pó",e:"Grandma (maternal)"},
    {c:"朋友",p:"péng yǒu",e:"Friend",i:"handshake"},
    {c:"太阳",p:"tài yáng",e:"Sun",i:"sun-with-face"},
    {c:"月亮",p:"yuè liang",e:"Moon",i:"crescent-moon"},
    {c:"星星",p:"xīng xing",e:"Star",i:"glowing-star"},
    {c:"苹果",p:"píng guǒ",e:"Apple",i:"red-apple"},
    {c:"香蕉",p:"xiāng jiāo",e:"Banana",i:"banana"},
    {c:"西瓜",p:"xī guā",e:"Watermelon",i:"watermelon"},
    {c:"牛奶",p:"niú nǎi",e:"Milk",i:"glass-of-milk"},
    {c:"米饭",p:"mǐ fàn",e:"Rice",i:"cooked-rice"},
    {c:"面包",p:"miàn bāo",e:"Bread",i:"bread"},
    {c:"鸡蛋",p:"jī dàn",e:"Egg",i:"egg"},
    {c:"水果",p:"shuǐ guǒ",e:"Fruit"},
    {c:"吃",p:"chī",e:"Eat",i:"fork-and-knife"},{c:"喝",p:"hē",e:"Drink",i:"cup-with-straw"},
    {c:"跑",p:"pǎo",e:"Run",i:"person-running"},{c:"走",p:"zǒu",e:"Walk",i:"person-walking"},
    {c:"看",p:"kàn",e:"Look",i:"eyes"},{c:"听",p:"tīng",e:"Listen",i:"ear"},
    {c:"说",p:"shuō",e:"Say"},{c:"读",p:"dú",e:"Read"},
    {c:"写",p:"xiě",e:"Write",i:"pencil"},{c:"来",p:"lái",e:"Come"},
    {c:"去",p:"qù",e:"Go"},{c:"坐",p:"zuò",e:"Sit"},
    {c:"站",p:"zhàn",e:"Stand"},{c:"笑",p:"xiào",e:"Laugh"},
    {c:"哭",p:"kū",e:"Cry"},{c:"睡",p:"shuì",e:"Sleep"},
    {c:"飞",p:"fēi",e:"Fly"},{c:"游",p:"yóu",e:"Swim"},
    {c:"唱",p:"chàng",e:"Sing"},{c:"跳",p:"tiào",e:"Jump"},
    {c:"打",p:"dǎ",e:"Hit"},{c:"拉",p:"lā",e:"Pull"},
    {c:"推",p:"tuī",e:"Push"},{c:"抱",p:"bào",e:"Hug"},
    {c:"爬",p:"pá",e:"Climb"},{c:"踢",p:"tī",e:"Kick"},
    {c:"扔",p:"rēng",e:"Throw"},{c:"接",p:"jiē",e:"Catch"},
    {c:"刷牙",p:"shuā yá",e:"Brush teeth"},{c:"洗手",p:"xǐ shǒu",e:"Wash hands"},
    {c:"起床",p:"qǐ chuáng",e:"Get up"},{c:"睡觉",p:"shuì jiào",e:"Go to sleep"},
    {c:"上学",p:"shàng xué",e:"Go to school"},{c:"回家",p:"huí jiā",e:"Go home"},
    {c:"吃饭",p:"chī fàn",e:"Eat a meal"},{c:"喝水",p:"hē shuǐ",e:"Drink water"},
    {c:"玩具",p:"wán jù",e:"Toy"},{c:"球",p:"qiú",e:"Ball",i:"soccer-ball"},
    {c:"娃娃",p:"wá wa",e:"Doll"},{c:"颜色",p:"yán sè",e:"Color"},
    {c:"甜",p:"tián",e:"Sweet"},{c:"酸",p:"suān",e:"Sour"},
    {c:"苦",p:"kǔ",e:"Bitter"},{c:"辣",p:"là",e:"Spicy"},
    {c:"咸",p:"xián",e:"Salty"},{c:"饱",p:"bǎo",e:"Full (stomach)"},
    {c:"猴子",p:"hóu zi",e:"Monkey",i:"monkey-face"},
    {c:"大象",p:"dà xiàng",e:"Elephant",i:"elephant"},
    {c:"熊猫",p:"xióng māo",e:"Panda"},{c:"狮子",p:"shī zi",e:"Lion",i:"lion"},
    {c:"长颈鹿",p:"cháng jǐng lù",e:"Giraffe",i:"giraffe"},
    {c:"企鹅",p:"qǐ é",e:"Penguin",i:"penguin"},
    {c:"海豚",p:"hǎi tún",e:"Dolphin"},{c:"鲨鱼",p:"shā yú",e:"Shark"},
    {c:"蜜蜂",p:"mì fēng",e:"Bee"},{c:"蚂蚁",p:"mǎ yǐ",e:"Ant"},
    {c:"乌龟",p:"wū guī",e:"Turtle",i:"turtle"},
    {c:"青蛙",p:"qīng wā",e:"Frog",i:"frog"},
    {c:"蜘蛛",p:"zhī zhū",e:"Spider"},{c:"老鼠",p:"lǎo shǔ",e:"Mouse/Rat"},
    // More daily phrases & verbs
    {c:"谁",p:"shuí",e:"Who"},{c:"哪",p:"nǎ",e:"Which"},
    {c:"怎么样",p:"zěn me yàng",e:"How is it"},
    {c:"多大",p:"duō dà",e:"How old"},{c:"几岁",p:"jǐ suì",e:"How old (age)"},
    {c:"叫",p:"jiào",e:"Called/Named"},{c:"是",p:"shì",e:"Is/Am/Are"},
    {c:"有",p:"yǒu",e:"Have"},{c:"没有",p:"méi yǒu",e:"Don't have"},
    {c:"不",p:"bù",e:"Not"},{c:"很",p:"hěn",e:"Very"},
    {c:"也",p:"yě",e:"Also"},{c:"都",p:"dōu",e:"All"},
    {c:"在",p:"zài",e:"At/In"},{c:"和",p:"hé",e:"And"},
    {c:"的",p:"de",e:"(possessive)"},{c:"了",p:"le",e:"(past tense)"},
    {c:"吗",p:"ma",e:"(question)"},{c:"呢",p:"ne",e:"(what about)"},
    {c:"会",p:"huì",e:"Can/Will"},{c:"能",p:"néng",e:"Can/Able"},
    {c:"要",p:"yào",e:"Want/Need"},{c:"给",p:"gěi",e:"Give/For"},
    {c:"让",p:"ràng",e:"Let"},{c:"把",p:"bǎ",e:"(object marker)"},
    {c:"被",p:"bèi",e:"(passive marker)"},{c:"着",p:"zhe",e:"(-ing, ongoing)"},
    {c:"过",p:"guò",e:"(experience)"},{c:"完",p:"wán",e:"Finish"},
    // Body & health for kids
    {c:"生病",p:"shēng bìng",e:"Get sick"},{c:"疼",p:"téng",e:"Hurt/Pain"},
    {c:"痒",p:"yǎng",e:"Itchy"},{c:"流鼻涕",p:"liú bí tì",e:"Runny nose"},
    {c:"打喷嚏",p:"dǎ pēn tì",e:"Sneeze"},
    // Weather for kids
    {c:"晴天",p:"qíng tiān",e:"Sunny day",i:"sun"},
    {c:"阴天",p:"yīn tiān",e:"Cloudy day",i:"cloud"},
    {c:"刮风",p:"guā fēng",e:"Windy"},{c:"打雷",p:"dǎ léi",e:"Thunder"},
    {c:"闪电",p:"shǎn diàn",e:"Lightning",i:"high-voltage"},
  ],
  4: [
    {c:"学校",p:"xué xiào",e:"School",i:"school"},
    {c:"老师",p:"lǎo shī",e:"Teacher",i:"woman-teacher"},
    {c:"学生",p:"xué shēng",e:"Student",i:"backpack"},
    {c:"同学",p:"tóng xué",e:"Classmate"},{c:"书",p:"shū",e:"Book",i:"open-book"},
    {c:"笔",p:"bǐ",e:"Pen",i:"pencil"},{c:"纸",p:"zhǐ",e:"Paper"},
    {c:"教室",p:"jiào shì",e:"Classroom"},{c:"作业",p:"zuò yè",e:"Homework"},
    {c:"考试",p:"kǎo shì",e:"Exam"},{c:"课",p:"kè",e:"Class/Lesson"},
    {c:"电话",p:"diàn huà",e:"Phone",i:"mobile-phone"},
    {c:"时间",p:"shí jiān",e:"Time",i:"alarm-clock"},
    {c:"今天",p:"jīn tiān",e:"Today",i:"calendar"},
    {c:"明天",p:"míng tiān",e:"Tomorrow",i:"sunrise"},
    {c:"昨天",p:"zuó tiān",e:"Yesterday"},{c:"早上",p:"zǎo shang",e:"Morning"},
    {c:"晚上",p:"wǎn shang",e:"Evening",i:"night-with-stars"},
    {c:"中午",p:"zhōng wǔ",e:"Noon"},{c:"下午",p:"xià wǔ",e:"Afternoon"},
    {c:"上午",p:"shàng wǔ",e:"Late morning"},{c:"现在",p:"xiàn zài",e:"Now"},
    {c:"小时",p:"xiǎo shí",e:"Hour"},{c:"分钟",p:"fēn zhōng",e:"Minute"},
    {c:"高兴",p:"gāo xìng",e:"Happy",i:"grinning-face-with-big-eyes"},
    {c:"快乐",p:"kuài lè",e:"Joyful",i:"partying-face"},
    {c:"难过",p:"nán guò",e:"Sad",i:"crying-face"},
    {c:"生气",p:"shēng qì",e:"Angry",i:"angry-face"},
    {c:"害怕",p:"hài pà",e:"Scared"},{c:"漂亮",p:"piào liang",e:"Pretty"},
    {c:"可爱",p:"kě ài",e:"Cute"},{c:"左",p:"zuǒ",e:"Left"},
    {c:"右",p:"yòu",e:"Right"},{c:"前",p:"qián",e:"Front"},
    {c:"后",p:"hòu",e:"Behind"},{c:"里",p:"lǐ",e:"Inside"},
    {c:"外",p:"wài",e:"Outside"},{c:"桌子",p:"zhuō zi",e:"Table"},
    {c:"椅子",p:"yǐ zi",e:"Chair"},{c:"床",p:"chuáng",e:"Bed"},
    {c:"灯",p:"dēng",e:"Light",i:"light-bulb"},{c:"窗",p:"chuāng",e:"Window"},
    {c:"筷子",p:"kuài zi",e:"Chopsticks",i:"chopsticks"},
    {c:"碗",p:"wǎn",e:"Bowl"},{c:"杯子",p:"bēi zi",e:"Cup"},
    {c:"医生",p:"yī shēng",e:"Doctor",i:"man-health-worker"},
    {c:"家",p:"jiā",e:"Home",i:"house"},{c:"房子",p:"fáng zi",e:"House"},
    {c:"房间",p:"fáng jiān",e:"Room"},{c:"厨房",p:"chú fáng",e:"Kitchen"},
    {c:"卧室",p:"wò shì",e:"Bedroom"},{c:"客厅",p:"kè tīng",e:"Living room"},
    {c:"卫生间",p:"wèi shēng jiān",e:"Bathroom"},
    {c:"钱",p:"qián",e:"Money"},{c:"东西",p:"dōng xi",e:"Thing/Stuff"},
    {c:"衣服",p:"yī fu",e:"Clothes",i:"shirt"},
    {c:"裤子",p:"kù zi",e:"Pants"},{c:"鞋子",p:"xié zi",e:"Shoes",i:"running-shoe"},
    {c:"帽子",p:"mào zi",e:"Hat"},{c:"裙子",p:"qún zi",e:"Skirt"},
    {c:"袜子",p:"wà zi",e:"Socks"},{c:"手套",p:"shǒu tào",e:"Gloves"},
    {c:"围巾",p:"wéi jīn",e:"Scarf"},{c:"雨伞",p:"yǔ sǎn",e:"Umbrella"},
    {c:"书包",p:"shū bāo",e:"Schoolbag",i:"backpack"},
    {c:"铅笔",p:"qiān bǐ",e:"Pencil",i:"pencil"},
    {c:"橡皮",p:"xiàng pí",e:"Eraser"},{c:"尺子",p:"chǐ zi",e:"Ruler"},
    {c:"黑板",p:"hēi bǎn",e:"Blackboard"},{c:"粉笔",p:"fěn bǐ",e:"Chalk"},
    {c:"地图",p:"dì tú",e:"Map"},{c:"字典",p:"zì diǎn",e:"Dictionary"},
    {c:"年",p:"nián",e:"Year"},{c:"星期",p:"xīng qī",e:"Week"},
    {c:"星期一",p:"xīng qī yī",e:"Monday"},{c:"星期二",p:"xīng qī èr",e:"Tuesday"},
    {c:"星期三",p:"xīng qī sān",e:"Wednesday"},{c:"星期四",p:"xīng qī sì",e:"Thursday"},
    {c:"星期五",p:"xīng qī wǔ",e:"Friday"},{c:"星期六",p:"xīng qī liù",e:"Saturday"},
    {c:"星期天",p:"xīng qī tiān",e:"Sunday"},{c:"生日",p:"shēng rì",e:"Birthday",i:"birthday-cake"},
    {c:"礼物",p:"lǐ wù",e:"Gift",i:"wrapped-gift"},
    {c:"节日",p:"jié rì",e:"Holiday"},{c:"春节",p:"chūn jié",e:"Chinese New Year"},
    {c:"圣诞节",p:"shèng dàn jié",e:"Christmas",i:"christmas-tree"},
    {c:"中秋节",p:"zhōng qiū jié",e:"Mid-Autumn Festival"},
    {c:"电梯",p:"diàn tī",e:"Elevator"},{c:"楼梯",p:"lóu tī",e:"Stairs"},
    {c:"厕所",p:"cè suǒ",e:"Toilet"},{c:"镜子",p:"jìng zi",e:"Mirror"},
    {c:"钥匙",p:"yào shi",e:"Key"},{c:"锁",p:"suǒ",e:"Lock"},
    {c:"闹钟",p:"nào zhōng",e:"Alarm clock"},{c:"日历",p:"rì lì",e:"Calendar"},
    {c:"空调",p:"kōng tiáo",e:"Air conditioner"},{c:"冰箱",p:"bīng xiāng",e:"Refrigerator"},
    {c:"洗衣机",p:"xǐ yī jī",e:"Washing machine"},{c:"微波炉",p:"wēi bō lú",e:"Microwave"},
    {c:"吸尘器",p:"xī chén qì",e:"Vacuum cleaner"},
    // Occupations kids know
    {c:"警察",p:"jǐng chá",e:"Police"},{c:"消防员",p:"xiāo fáng yuán",e:"Firefighter"},
    {c:"护士",p:"hù shi",e:"Nurse"},{c:"厨师",p:"chú shī",e:"Chef"},
    {c:"司机",p:"sī jī",e:"Driver"},{c:"农民",p:"nóng mín",e:"Farmer"},
    {c:"飞行员",p:"fēi xíng yuán",e:"Pilot"},{c:"宇航员",p:"yǔ háng yuán",e:"Astronaut"},
    // Materials
    {c:"木头",p:"mù tou",e:"Wood"},{c:"玻璃",p:"bō li",e:"Glass"},
    {c:"塑料",p:"sù liào",e:"Plastic"},{c:"金属",p:"jīn shǔ",e:"Metal"},
    {c:"布",p:"bù",e:"Cloth"},{c:"皮",p:"pí",e:"Leather/Skin"},
    {c:"纸板",p:"zhǐ bǎn",e:"Cardboard"},{c:"绳子",p:"shéng zi",e:"Rope"},
    // Shapes
    {c:"圆",p:"yuán",e:"Round"},{c:"方",p:"fāng",e:"Square"},
    {c:"三角",p:"sān jiǎo",e:"Triangle"},{c:"直线",p:"zhí xiàn",e:"Straight line"},
    {c:"弯",p:"wān",e:"Curved"},{c:"尖",p:"jiān",e:"Pointed"},
    {c:"平",p:"píng",e:"Flat"},{c:"厚",p:"hòu",e:"Thick"},
    // Math basics
    {c:"数字",p:"shù zì",e:"Number"},{c:"加法",p:"jiā fǎ",e:"Addition"},
    {c:"减法",p:"jiǎn fǎ",e:"Subtraction"},{c:"乘法",p:"chéng fǎ",e:"Multiplication"},
    {c:"答案",p:"dá àn",e:"Answer"},{c:"问题",p:"wèn tí",e:"Question"},
    // Nature observations
    {c:"影子",p:"yǐng zi",e:"Shadow"},{c:"光",p:"guāng",e:"Light"},
    {c:"声音",p:"shēng yīn",e:"Sound"},{c:"味道",p:"wèi dào",e:"Smell/Taste"},
    {c:"温度",p:"wēn dù",e:"Temperature"},
    {c:"重力",p:"zhòng lì",e:"Gravity"},{c:"磁铁",p:"cí tiě",e:"Magnet"},
  ],
  5: [
    {c:"飞机",p:"fēi jī",e:"Airplane",i:"airplane"},
    {c:"汽车",p:"qì chē",e:"Car",i:"automobile"},
    {c:"火车",p:"huǒ chē",e:"Train",i:"locomotive"},
    {c:"公共汽车",p:"gōng gòng qì chē",e:"Bus",i:"bus"},
    {c:"自行车",p:"zì xíng chē",e:"Bicycle",i:"bicycle"},
    {c:"地铁",p:"dì tiě",e:"Subway"},{c:"船",p:"chuán",e:"Boat",i:"sailboat"},
    {c:"出租车",p:"chū zū chē",e:"Taxi"},
    {c:"图书馆",p:"tú shū guǎn",e:"Library",i:"books"},
    {c:"动物园",p:"dòng wù yuán",e:"Zoo",i:"lion"},
    {c:"医院",p:"yī yuàn",e:"Hospital"},{c:"超市",p:"chāo shì",e:"Supermarket"},
    {c:"公园",p:"gōng yuán",e:"Park"},{c:"电影院",p:"diàn yǐng yuàn",e:"Cinema"},
    {c:"机场",p:"jī chǎng",e:"Airport"},{c:"银行",p:"yín háng",e:"Bank"},
    {c:"餐厅",p:"cān tīng",e:"Restaurant"},{c:"宾馆",p:"bīn guǎn",e:"Hotel"},
    {c:"商店",p:"shāng diàn",e:"Shop"},{c:"市场",p:"shì chǎng",e:"Market"},
    {c:"巧克力",p:"qiǎo kè lì",e:"Chocolate",i:"chocolate-bar"},
    {c:"冰淇淋",p:"bīng qí lín",e:"Ice cream"},
    {c:"饺子",p:"jiǎo zi",e:"Dumpling",i:"dumpling"},
    {c:"面条",p:"miàn tiáo",e:"Noodles",i:"steaming-bowl"},
    {c:"蛋糕",p:"dàn gāo",e:"Cake",i:"birthday-cake"},
    {c:"糖果",p:"táng guǒ",e:"Candy",i:"candy"},
    {c:"茶",p:"chá",e:"Tea",i:"teacup-without-handle"},
    {c:"咖啡",p:"kā fēi",e:"Coffee",i:"hot-beverage"},
    {c:"果汁",p:"guǒ zhī",e:"Juice"},{c:"可乐",p:"kě lè",e:"Cola"},
    {c:"牛肉",p:"niú ròu",e:"Beef"},{c:"猪肉",p:"zhū ròu",e:"Pork"},
    {c:"鸡肉",p:"jī ròu",e:"Chicken meat"},{c:"蔬菜",p:"shū cài",e:"Vegetables"},
    {c:"葡萄",p:"pú tao",e:"Grape",i:"grapes"},
    {c:"草莓",p:"cǎo méi",e:"Strawberry",i:"strawberry"},
    {c:"橙子",p:"chéng zi",e:"Orange",i:"tangerine"},
    {c:"桃子",p:"táo zi",e:"Peach",i:"peach"},{c:"梨",p:"lí",e:"Pear"},
    {c:"唱歌",p:"chàng gē",e:"Sing",i:"microphone"},
    {c:"跳舞",p:"tiào wǔ",e:"Dance",i:"woman-dancing"},
    {c:"画画",p:"huà huà",e:"Draw",i:"artist-palette"},
    {c:"游泳",p:"yóu yǒng",e:"Swim",i:"person-swimming"},
    {c:"踢足球",p:"tī zú qiú",e:"Play soccer",i:"soccer-ball"},
    {c:"打篮球",p:"dǎ lán qiú",e:"Play basketball",i:"basketball"},
    {c:"聪明",p:"cōng míng",e:"Smart",i:"brain"},
    {c:"勇敢",p:"yǒng gǎn",e:"Brave"},{c:"认真",p:"rèn zhēn",e:"Serious"},
    {c:"快",p:"kuài",e:"Fast"},{c:"慢",p:"màn",e:"Slow"},
    {c:"多",p:"duō",e:"Many"},{c:"少",p:"shǎo",e:"Few"},
    {c:"长",p:"cháng",e:"Long"},{c:"短",p:"duǎn",e:"Short"},
    {c:"高",p:"gāo",e:"Tall"},{c:"矮",p:"ǎi",e:"Short (height)"},
    {c:"胖",p:"pàng",e:"Fat"},{c:"瘦",p:"shòu",e:"Thin"},
    {c:"新",p:"xīn",e:"New"},{c:"旧",p:"jiù",e:"Old (things)"},
    {c:"冷",p:"lěng",e:"Cold"},{c:"热",p:"rè",e:"Hot"},
    {c:"好",p:"hǎo",e:"Good"},{c:"坏",p:"huài",e:"Bad"},
    {c:"对",p:"duì",e:"Correct"},{c:"错",p:"cuò",e:"Wrong"},
    {c:"远",p:"yuǎn",e:"Far"},{c:"近",p:"jìn",e:"Near"},
    {c:"轻",p:"qīng",e:"Light (weight)"},{c:"重",p:"zhòng",e:"Heavy"},
    {c:"干净",p:"gān jìng",e:"Clean"},{c:"脏",p:"zāng",e:"Dirty"},
    {c:"容易",p:"róng yì",e:"Easy"},{c:"难",p:"nán",e:"Difficult"},
    {c:"便宜",p:"pián yi",e:"Cheap"},{c:"贵",p:"guì",e:"Expensive"},
    {c:"忙",p:"máng",e:"Busy"},{c:"累",p:"lèi",e:"Tired"},
    {c:"饿",p:"è",e:"Hungry"},{c:"渴",p:"kě",e:"Thirsty"},
    {c:"胖",p:"pàng",e:"Chubby"},{c:"瘦",p:"shòu",e:"Thin"},
    {c:"年轻",p:"nián qīng",e:"Young"},{c:"老",p:"lǎo",e:"Old"},
    {c:"厚",p:"hòu",e:"Thick"},{c:"薄",p:"báo",e:"Thin (flat)"},
    {c:"深",p:"shēn",e:"Deep"},{c:"浅",p:"qiǎn",e:"Shallow"},
    {c:"宽",p:"kuān",e:"Wide"},{c:"窄",p:"zhǎi",e:"Narrow"},
    {c:"满",p:"mǎn",e:"Full"},{c:"空",p:"kōng",e:"Empty"},
    {c:"亮",p:"liàng",e:"Bright"},{c:"暗",p:"àn",e:"Dark"},
    {c:"软",p:"ruǎn",e:"Soft"},{c:"硬",p:"yìng",e:"Hard"},
    {c:"湿",p:"shī",e:"Wet"},{c:"干",p:"gān",e:"Dry"},
    {c:"甜点",p:"tián diǎn",e:"Dessert"},{c:"零食",p:"líng shí",e:"Snack"},
    {c:"火锅",p:"huǒ guō",e:"Hot pot"},{c:"烧烤",p:"shāo kǎo",e:"BBQ"},
    {c:"寿司",p:"shòu sī",e:"Sushi"},{c:"披萨",p:"pī sà",e:"Pizza",i:"pizza"},
    {c:"汉堡",p:"hàn bǎo",e:"Hamburger"},{c:"三明治",p:"sān míng zhì",e:"Sandwich"},
    {c:"沙拉",p:"shā lā",e:"Salad"},{c:"豆腐",p:"dòu fu",e:"Tofu"},
    {c:"包子",p:"bāo zi",e:"Steamed bun"},{c:"馒头",p:"mán tou",e:"Plain bun"},
    {c:"粥",p:"zhōu",e:"Porridge"},{c:"汤",p:"tāng",e:"Soup"},
    {c:"醋",p:"cù",e:"Vinegar"},{c:"酱油",p:"jiàng yóu",e:"Soy sauce"},
    {c:"盘子",p:"pán zi",e:"Plate"},{c:"勺子",p:"sháo zi",e:"Spoon"},
    {c:"叉子",p:"chā zi",e:"Fork"},{c:"刀",p:"dāo",e:"Knife"},
    {c:"壶",p:"hú",e:"Pot/Kettle"},{c:"瓶子",p:"píng zi",e:"Bottle"},
    {c:"吉他",p:"jí tā",e:"Guitar",i:"guitar"},
    {c:"小提琴",p:"xiǎo tí qín",e:"Violin",i:"violin"},
    {c:"鼓",p:"gǔ",e:"Drum",i:"drum"},
    {c:"滑冰",p:"huá bīng",e:"Ice skating"},{c:"滑雪",p:"huá xuě",e:"Skiing"},
    {c:"骑马",p:"qí mǎ",e:"Horse riding"},{c:"钓鱼",p:"diào yú",e:"Fishing"},
    {c:"下棋",p:"xià qí",e:"Play chess"},{c:"跳绳",p:"tiào shéng",e:"Jump rope"},
    {c:"放风筝",p:"fàng fēng zhēng",e:"Fly a kite"},{c:"打乒乓球",p:"dǎ pīng pāng qiú",e:"Play ping pong"},
    {c:"打羽毛球",p:"dǎ yǔ máo qiú",e:"Play badminton"},
    {c:"运动",p:"yùn dòng",e:"Exercise/Sport"},
    // More food & kitchen
    {c:"炒饭",p:"chǎo fàn",e:"Fried rice"},{c:"炒面",p:"chǎo miàn",e:"Fried noodles"},
    {c:"春卷",p:"chūn juǎn",e:"Spring roll"},{c:"月饼",p:"yuè bǐng",e:"Mooncake"},
    {c:"粽子",p:"zòng zi",e:"Rice dumpling"},{c:"汤圆",p:"tāng yuán",e:"Sweet rice ball"},
    {c:"豆浆",p:"dòu jiāng",e:"Soy milk"},{c:"酸奶",p:"suān nǎi",e:"Yogurt"},
    {c:"花生",p:"huā shēng",e:"Peanut",i:"peanuts"},
    {c:"玉米",p:"yù mǐ",e:"Corn",i:"ear-of-corn"},
    {c:"土豆",p:"tǔ dòu",e:"Potato"},{c:"番茄",p:"fān qié",e:"Tomato",i:"tomato"},
    {c:"黄瓜",p:"huáng guā",e:"Cucumber"},{c:"胡萝卜",p:"hú luó bo",e:"Carrot"},
    {c:"白菜",p:"bái cài",e:"Chinese cabbage"},{c:"菠菜",p:"bō cài",e:"Spinach"},
    {c:"蘑菇",p:"mó gu",e:"Mushroom"},{c:"洋葱",p:"yáng cōng",e:"Onion"},
    {c:"大蒜",p:"dà suàn",e:"Garlic"},{c:"生姜",p:"shēng jiāng",e:"Ginger"},
    {c:"辣椒",p:"là jiāo",e:"Chili pepper",i:"hot-pepper"},
    // More household & daily life
    {c:"毛巾",p:"máo jīn",e:"Towel"},{c:"牙刷",p:"yá shuā",e:"Toothbrush"},
    {c:"牙膏",p:"yá gāo",e:"Toothpaste"},{c:"肥皂",p:"féi zào",e:"Soap"},
    {c:"洗发水",p:"xǐ fà shuǐ",e:"Shampoo"},{c:"梳子",p:"shū zi",e:"Comb"},
    {c:"电风扇",p:"diàn fēng shàn",e:"Fan (electric)"},
    {c:"暖气",p:"nuǎn qì",e:"Heating"},{c:"窗帘",p:"chuāng lián",e:"Curtain"},
    {c:"地毯",p:"dì tǎn",e:"Carpet"},{c:"沙发",p:"shā fā",e:"Sofa"},
    {c:"书架",p:"shū jià",e:"Bookshelf"},{c:"衣柜",p:"yī guì",e:"Wardrobe"},
    {c:"抽屉",p:"chōu ti",e:"Drawer"},{c:"花瓶",p:"huā píng",e:"Vase"},
    // Sports & games
    {c:"网球",p:"wǎng qiú",e:"Tennis",i:"tennis"},
    {c:"排球",p:"pái qiú",e:"Volleyball"},{c:"棒球",p:"bàng qiú",e:"Baseball"},
    {c:"高尔夫",p:"gāo ěr fū",e:"Golf"},{c:"拳击",p:"quán jī",e:"Boxing"},
    {c:"武术",p:"wǔ shù",e:"Martial arts"},{c:"太极拳",p:"tài jí quán",e:"Tai chi"},
    {c:"瑜伽",p:"yú jiā",e:"Yoga"},{c:"体操",p:"tǐ cāo",e:"Gymnastics"},
    {c:"田径",p:"tián jìng",e:"Track and field"},
    {c:"冠军",p:"guàn jūn",e:"Champion"},{c:"奖牌",p:"jiǎng pái",e:"Medal"},
    {c:"金牌",p:"jīn pái",e:"Gold medal"},{c:"银牌",p:"yín pái",e:"Silver medal"},
    {c:"铜牌",p:"tóng pái",e:"Bronze medal"},
    {c:"奥运会",p:"ào yùn huì",e:"Olympics"},
    {c:"世界杯",p:"shì jiè bēi",e:"World Cup"},
  ],
  6: [
    {c:"电脑",p:"diàn nǎo",e:"Computer",i:"laptop"},
    {c:"电视",p:"diàn shì",e:"TV",i:"television"},
    {c:"手机",p:"shǒu jī",e:"Cell phone",i:"mobile-phone"},
    {c:"音乐",p:"yīn yuè",e:"Music",i:"musical-notes"},
    {c:"钢琴",p:"gāng qín",e:"Piano",i:"musical-keyboard"},
    {c:"恐龙",p:"kǒng lóng",e:"Dinosaur",i:"t-rex"},
    {c:"蝴蝶",p:"hú dié",e:"Butterfly",i:"butterfly"},
    {c:"彩虹",p:"cǎi hóng",e:"Rainbow",i:"rainbow"},
    {c:"眼睛",p:"yǎn jīng",e:"Eyes",i:"eyes"},
    {c:"鼻子",p:"bí zi",e:"Nose"},{c:"嘴巴",p:"zuǐ ba",e:"Mouth"},
    {c:"牙齿",p:"yá chǐ",e:"Teeth"},{c:"头发",p:"tóu fa",e:"Hair"},
    {c:"手指",p:"shǒu zhǐ",e:"Finger"},{c:"脚",p:"jiǎo",e:"Foot"},
    {c:"腿",p:"tuǐ",e:"Leg"},{c:"肚子",p:"dù zi",e:"Belly"},
    {c:"脸",p:"liǎn",e:"Face"},{c:"背",p:"bèi",e:"Back"},
    {c:"肩膀",p:"jiān bǎng",e:"Shoulder"},{c:"膝盖",p:"xī gài",e:"Knee"},
    {c:"天气",p:"tiān qì",e:"Weather"},{c:"下雨",p:"xià yǔ",e:"Raining"},
    {c:"下雪",p:"xià xuě",e:"Snowing"},{c:"春天",p:"chūn tiān",e:"Spring"},
    {c:"夏天",p:"xià tiān",e:"Summer",i:"sun"},
    {c:"秋天",p:"qiū tiān",e:"Autumn",i:"fallen-leaf"},
    {c:"冬天",p:"dōng tiān",e:"Winter"},{c:"温度",p:"wēn dù",e:"Temperature"},
    {c:"知道",p:"zhī dào",e:"Know"},{c:"喜欢",p:"xǐ huān",e:"Like"},
    {c:"可以",p:"kě yǐ",e:"Can"},{c:"应该",p:"yīng gāi",e:"Should"},
    {c:"需要",p:"xū yào",e:"Need"},{c:"想",p:"xiǎng",e:"Think/Want"},
    {c:"做",p:"zuò",e:"Do/Make"},{c:"给",p:"gěi",e:"Give"},
    {c:"买",p:"mǎi",e:"Buy"},{c:"卖",p:"mài",e:"Sell"},
    {c:"开",p:"kāi",e:"Open"},{c:"关",p:"guān",e:"Close"},
    {c:"穿",p:"chuān",e:"Wear"},{c:"洗",p:"xǐ",e:"Wash"},
    {c:"玩",p:"wán",e:"Play"},{c:"学",p:"xué",e:"Study"},
    {c:"教",p:"jiāo",e:"Teach"},{c:"帮",p:"bāng",e:"Help"},
    {c:"找",p:"zhǎo",e:"Find"},{c:"用",p:"yòng",e:"Use"},
    {c:"拿",p:"ná",e:"Take"},{c:"放",p:"fàng",e:"Put"},
    {c:"送",p:"sòng",e:"Send/Give"},{c:"住",p:"zhù",e:"Live"},
    {c:"工作",p:"gōng zuò",e:"Work"},{c:"休息",p:"xiū xi",e:"Rest"},
    {c:"等",p:"děng",e:"Wait"},{c:"回",p:"huí",e:"Return"},
    {c:"问",p:"wèn",e:"Ask"},{c:"答",p:"dá",e:"Answer"},
    {c:"试",p:"shì",e:"Try"},{c:"让",p:"ràng",e:"Let/Allow"},
    {c:"带",p:"dài",e:"Bring"},{c:"换",p:"huàn",e:"Change/Exchange"},
    {c:"修",p:"xiū",e:"Fix"},{c:"搬",p:"bān",e:"Move (objects)"},
    {c:"我",p:"wǒ",e:"I/Me"},{c:"你",p:"nǐ",e:"You"},
    {c:"他",p:"tā",e:"He"},{c:"她",p:"tā",e:"She"},
    {c:"我们",p:"wǒ men",e:"We"},{c:"你们",p:"nǐ men",e:"You (plural)"},
    {c:"他们",p:"tā men",e:"They"},{c:"这",p:"zhè",e:"This"},
    {c:"那",p:"nà",e:"That"},{c:"什么",p:"shén me",e:"What"},
    {c:"哪里",p:"nǎ lǐ",e:"Where"},{c:"谁",p:"shuí",e:"Who"},
    {c:"怎么",p:"zěn me",e:"How"},{c:"为什么",p:"wèi shén me",e:"Why"},
    {c:"多少",p:"duō shǎo",e:"How many"},{c:"几",p:"jǐ",e:"How many (small)"},
    {c:"百",p:"bǎi",e:"Hundred"},{c:"千",p:"qiān",e:"Thousand"},
    {c:"万",p:"wàn",e:"Ten thousand"},{c:"零",p:"líng",e:"Zero"},
    {c:"中国",p:"zhōng guó",e:"China"},{c:"美国",p:"měi guó",e:"America"},
    {c:"日本",p:"rì běn",e:"Japan"},{c:"世界",p:"shì jiè",e:"World"},
    {c:"地球",p:"dì qiú",e:"Earth",i:"globe-showing-asia-australia"},
    {c:"韩国",p:"hán guó",e:"South Korea"},{c:"德国",p:"dé guó",e:"Germany"},
    {c:"加拿大",p:"jiā ná dà",e:"Canada"},{c:"澳大利亚",p:"ào dà lì yà",e:"Australia"},
    {c:"印度",p:"yìn dù",e:"India"},{c:"巴西",p:"bā xī",e:"Brazil"},
    {c:"俄罗斯",p:"é luó sī",e:"Russia"},{c:"非洲",p:"fēi zhōu",e:"Africa"},
    {c:"欧洲",p:"ōu zhōu",e:"Europe"},{c:"亚洲",p:"yà zhōu",e:"Asia"},
    {c:"北京",p:"běi jīng",e:"Beijing"},{c:"上海",p:"shàng hǎi",e:"Shanghai"},
    {c:"香港",p:"xiāng gǎng",e:"Hong Kong"},{c:"台湾",p:"tái wān",e:"Taiwan"},
    {c:"意思",p:"yì si",e:"Meaning"},{c:"发音",p:"fā yīn",e:"Pronunciation"},
    {c:"句子",p:"jù zi",e:"Sentence"},{c:"段落",p:"duàn luò",e:"Paragraph"},
    {c:"文章",p:"wén zhāng",e:"Article"},{c:"作文",p:"zuò wén",e:"Essay/Composition"},
    {c:"诗",p:"shī",e:"Poem"},{c:"歌词",p:"gē cí",e:"Lyrics"},
    {c:"成语",p:"chéng yǔ",e:"Idiom (4-char)"},{c:"谚语",p:"yàn yǔ",e:"Proverb"},
    {c:"笑话",p:"xiào hua",e:"Joke"},{c:"谜语",p:"mí yǔ",e:"Riddle"},
    {c:"感冒",p:"gǎn mào",e:"Cold (illness)"},{c:"发烧",p:"fā shāo",e:"Fever"},
    {c:"咳嗽",p:"ké sou",e:"Cough"},{c:"头疼",p:"tóu téng",e:"Headache"},
    {c:"肚子疼",p:"dù zi téng",e:"Stomachache"},{c:"药",p:"yào",e:"Medicine"},
    {c:"打针",p:"dǎ zhēn",e:"Injection"},{c:"检查",p:"jiǎn chá",e:"Check/Examine"},
    {c:"牙医",p:"yá yī",e:"Dentist"},{c:"护士",p:"hù shi",e:"Nurse"},
    {c:"急救",p:"jí jiù",e:"First aid"},{c:"受伤",p:"shòu shāng",e:"Injured"},
    {c:"紧张",p:"jǐn zhāng",e:"Nervous"},{c:"兴奋",p:"xīng fèn",e:"Excited"},
    {c:"无聊",p:"wú liáo",e:"Bored"},{c:"骄傲",p:"jiāo ào",e:"Proud"},
    {c:"羡慕",p:"xiàn mù",e:"Envy"},{c:"后悔",p:"hòu huǐ",e:"Regret"},
    {c:"感动",p:"gǎn dòng",e:"Moved (emotionally)"},
    {c:"满意",p:"mǎn yì",e:"Satisfied"},{c:"失望",p:"shī wàng",e:"Disappointed"},
    {c:"孤独",p:"gū dú",e:"Lonely"},{c:"温暖",p:"wēn nuǎn",e:"Warm"},
    // Cooking & eating
    {c:"煮",p:"zhǔ",e:"Boil"},{c:"炒",p:"chǎo",e:"Stir-fry"},
    {c:"烤",p:"kǎo",e:"Roast/Bake"},{c:"蒸",p:"zhēng",e:"Steam"},
    {c:"煎",p:"jiān",e:"Pan-fry"},{c:"切",p:"qiē",e:"Cut"},
    {c:"剥",p:"bāo",e:"Peel"},{c:"搅拌",p:"jiǎo bàn",e:"Stir/Mix"},
    {c:"味道好",p:"wèi dào hǎo",e:"Tastes good"},
    {c:"难吃",p:"nán chī",e:"Tastes bad"},{c:"好吃",p:"hǎo chī",e:"Delicious"},
    {c:"好喝",p:"hǎo hē",e:"Tastes good (drink)"},
    // Shopping
    {c:"价钱",p:"jià qian",e:"Price"},{c:"打折",p:"dǎ zhé",e:"Discount"},
    {c:"收银台",p:"shōu yín tái",e:"Cashier"},{c:"找钱",p:"zhǎo qián",e:"Give change"},
    {c:"信用卡",p:"xìn yòng kǎ",e:"Credit card"},
    {c:"现金",p:"xiàn jīn",e:"Cash"},{c:"付款",p:"fù kuǎn",e:"Pay"},
    {c:"退货",p:"tuì huò",e:"Return goods"},{c:"换货",p:"huàn huò",e:"Exchange goods"},
    // Communication & tech
    {c:"短信",p:"duǎn xìn",e:"Text message"},{c:"微信",p:"wēi xìn",e:"WeChat"},
    {c:"视频",p:"shì pín",e:"Video"},{c:"直播",p:"zhí bō",e:"Livestream"},
    {c:"游戏",p:"yóu xì",e:"Game"},{c:"动画片",p:"dòng huà piàn",e:"Cartoon"},
    {c:"广播",p:"guǎng bō",e:"Broadcast"},{c:"耳机",p:"ěr jī",e:"Headphones",i:"headphone"},
    // More places
    {c:"游乐场",p:"yóu lè chǎng",e:"Amusement park"},
    {c:"博物馆",p:"bó wù guǎn",e:"Museum"},{c:"体育馆",p:"tǐ yù guǎn",e:"Stadium"},
    {c:"游泳池",p:"yóu yǒng chí",e:"Swimming pool"},
    {c:"教堂",p:"jiào táng",e:"Church"},{c:"寺庙",p:"sì miào",e:"Temple"},
    {c:"城堡",p:"chéng bǎo",e:"Castle"},{c:"宫殿",p:"gōng diàn",e:"Palace"},
    {c:"塔",p:"tǎ",e:"Tower"},{c:"长城",p:"cháng chéng",e:"Great Wall"},
    // Miscellaneous
    {c:"礼貌",p:"lǐ mào",e:"Polite"},{c:"粗鲁",p:"cū lǔ",e:"Rude"},
    {c:"安静",p:"ān jìng",e:"Quiet"},{c:"吵",p:"chǎo",e:"Noisy"},
    {c:"整齐",p:"zhěng qí",e:"Tidy"},{c:"乱",p:"luàn",e:"Messy"},
    {c:"仔细",p:"zǐ xì",e:"Careful"},{c:"粗心",p:"cū xīn",e:"Careless"},
    {c:"勤快",p:"qín kuài",e:"Diligent"},{c:"懒",p:"lǎn",e:"Lazy"},
    {c:"严格",p:"yán gé",e:"Strict"},{c:"温柔",p:"wēn róu",e:"Gentle"},
    {c:"活泼",p:"huó po",e:"Lively"},{c:"内向",p:"nèi xiàng",e:"Introverted"},
    {c:"外向",p:"wài xiàng",e:"Extroverted"},{c:"善良",p:"shàn liáng",e:"Kind-hearted"},
  ],
  7: [
    {c:"环境",p:"huán jìng",e:"Environment"},{c:"保护",p:"bǎo hù",e:"Protect"},
    {c:"动物",p:"dòng wù",e:"Animal"},{c:"植物",p:"zhí wù",e:"Plant"},
    {c:"科学",p:"kē xué",e:"Science"},{c:"数学",p:"shù xué",e:"Math"},
    {c:"历史",p:"lì shǐ",e:"History"},{c:"地理",p:"dì lǐ",e:"Geography"},
    {c:"语文",p:"yǔ wén",e:"Chinese (subject)"},{c:"英语",p:"yīng yǔ",e:"English"},
    {c:"体育",p:"tǐ yù",e:"PE"},{c:"美术",p:"měi shù",e:"Art"},
    {c:"已经",p:"yǐ jīng",e:"Already"},{c:"还",p:"hái",e:"Still"},
    {c:"才",p:"cái",e:"Only then"},{c:"就",p:"jiù",e:"Then"},
    {c:"虽然",p:"suī rán",e:"Although"},{c:"但是",p:"dàn shì",e:"But"},
    {c:"因为",p:"yīn wèi",e:"Because"},{c:"所以",p:"suǒ yǐ",e:"So"},
    {c:"如果",p:"rú guǒ",e:"If"},{c:"或者",p:"huò zhě",e:"Or"},
    {c:"而且",p:"ér qiě",e:"Moreover"},{c:"然后",p:"rán hòu",e:"Then"},
    {c:"以前",p:"yǐ qián",e:"Before"},{c:"以后",p:"yǐ hòu",e:"After"},
    {c:"经常",p:"jīng cháng",e:"Often"},{c:"有时候",p:"yǒu shí hou",e:"Sometimes"},
    {c:"马上",p:"mǎ shàng",e:"Immediately"},{c:"突然",p:"tū rán",e:"Suddenly"},
    {c:"特别",p:"tè bié",e:"Especially"},{c:"非常",p:"fēi cháng",e:"Very"},
    {c:"必须",p:"bì xū",e:"Must"},{c:"可能",p:"kě néng",e:"Maybe"},
    {c:"一定",p:"yí dìng",e:"Certainly"},{c:"重要",p:"zhòng yào",e:"Important"},
    {c:"安全",p:"ān quán",e:"Safe"},{c:"危险",p:"wēi xiǎn",e:"Dangerous"},
    {c:"健康",p:"jiàn kāng",e:"Healthy"},{c:"努力",p:"nǔ lì",e:"Hard-working"},
    {c:"成功",p:"chéng gōng",e:"Success"},{c:"失败",p:"shī bài",e:"Failure"},
    {c:"发现",p:"fā xiàn",e:"Discover"},{c:"解决",p:"jiě jué",e:"Solve"},
    {c:"相信",p:"xiāng xìn",e:"Believe"},{c:"同意",p:"tóng yì",e:"Agree"},
    {c:"决定",p:"jué dìng",e:"Decide"},{c:"准备",p:"zhǔn bèi",e:"Prepare"},
    {c:"计划",p:"jì huà",e:"Plan"},{c:"开始",p:"kāi shǐ",e:"Begin"},
    {c:"结束",p:"jié shù",e:"End"},{c:"继续",p:"jì xù",e:"Continue"},
    {c:"完成",p:"wán chéng",e:"Complete"},{c:"变化",p:"biàn huà",e:"Change"},
    {c:"发展",p:"fā zhǎn",e:"Develop"},{c:"提高",p:"tí gāo",e:"Improve"},
    {c:"增加",p:"zēng jiā",e:"Increase"},{c:"减少",p:"jiǎn shǎo",e:"Decrease"},
    {c:"参加",p:"cān jiā",e:"Participate"},{c:"比赛",p:"bǐ sài",e:"Competition"},
    {c:"练习",p:"liàn xí",e:"Practice"},{c:"表演",p:"biǎo yǎn",e:"Perform"},
    {c:"注意",p:"zhù yì",e:"Pay attention"},{c:"记住",p:"jì zhù",e:"Remember"},
    {c:"忘记",p:"wàng jì",e:"Forget"},{c:"理解",p:"lǐ jiě",e:"Understand"},
    {c:"翻译",p:"fān yì",e:"Translate"},{c:"解释",p:"jiě shì",e:"Explain"},
    {c:"讨论",p:"tǎo lùn",e:"Discuss"},{c:"介绍",p:"jiè shào",e:"Introduce"},
    {c:"通知",p:"tōng zhī",e:"Notify"},{c:"邀请",p:"yāo qǐng",e:"Invite"},
    {c:"拒绝",p:"jù jué",e:"Refuse"},{c:"接受",p:"jiē shòu",e:"Accept"},
    {c:"感谢",p:"gǎn xiè",e:"Thank"},{c:"道歉",p:"dào qiàn",e:"Apologize"},
    {c:"表示",p:"biǎo shì",e:"Express"},{c:"希望",p:"xī wàng",e:"Hope"},
    {c:"担心",p:"dān xīn",e:"Worry"},{c:"生活",p:"shēng huó",e:"Life"},
    {c:"经历",p:"jīng lì",e:"Experience"},{c:"回忆",p:"huí yì",e:"Memory"},
    {c:"故事",p:"gù shi",e:"Story"},{c:"新闻",p:"xīn wén",e:"News"},
    {c:"报纸",p:"bào zhǐ",e:"Newspaper"},{c:"杂志",p:"zá zhì",e:"Magazine"},
    {c:"节目",p:"jié mù",e:"Program/Show"},{c:"电影",p:"diàn yǐng",e:"Movie"},
    {c:"照片",p:"zhào piàn",e:"Photo"},{c:"照相机",p:"zhào xiàng jī",e:"Camera"},
    {c:"网络",p:"wǎng luò",e:"Internet"},{c:"信息",p:"xìn xī",e:"Information"},
    {c:"密码",p:"mì mǎ",e:"Password"},{c:"地址",p:"dì zhǐ",e:"Address"},
    {c:"号码",p:"hào mǎ",e:"Number"},{c:"护照",p:"hù zhào",e:"Passport"},
    {c:"签证",p:"qiān zhèng",e:"Visa"},{c:"行李",p:"xíng li",e:"Luggage"},
    // Nature & geography
    {c:"沙漠",p:"shā mò",e:"Desert"},{c:"丛林",p:"cóng lín",e:"Jungle"},
    {c:"瀑布",p:"pù bù",e:"Waterfall"},{c:"火山",p:"huǒ shān",e:"Volcano"},
    {c:"地震",p:"dì zhèn",e:"Earthquake"},{c:"台风",p:"tái fēng",e:"Typhoon"},
    {c:"洪水",p:"hóng shuǐ",e:"Flood"},{c:"干旱",p:"gān hàn",e:"Drought"},
    {c:"海洋",p:"hǎi yáng",e:"Ocean"},{c:"大陆",p:"dà lù",e:"Continent"},
    {c:"半岛",p:"bàn dǎo",e:"Peninsula"},{c:"峡谷",p:"xiá gǔ",e:"Canyon"},
    {c:"平原",p:"píng yuán",e:"Plain"},{c:"盆地",p:"pén dì",e:"Basin"},
    // More verbs
    {c:"拥抱",p:"yōng bào",e:"Embrace"},{c:"握手",p:"wò shǒu",e:"Shake hands"},
    {c:"鼓励",p:"gǔ lì",e:"Encourage"},{c:"批评",p:"pī píng",e:"Criticize"},
    {c:"赞美",p:"zàn měi",e:"Praise"},{c:"安慰",p:"ān wèi",e:"Comfort"},
    {c:"原谅",p:"yuán liàng",e:"Forgive"},{c:"误会",p:"wù huì",e:"Misunderstand"},
    {c:"争论",p:"zhēng lùn",e:"Argue"},{c:"吵架",p:"chǎo jià",e:"Quarrel"},
    {c:"和好",p:"hé hǎo",e:"Make up"},{c:"分享",p:"fēn xiǎng",e:"Share"},
    {c:"比较",p:"bǐ jiào",e:"Compare"},{c:"猜",p:"cāi",e:"Guess"},
    {c:"选择",p:"xuǎn zé",e:"Choose"},{c:"放弃",p:"fàng qì",e:"Give up"},
    {c:"坚持",p:"jiān chí",e:"Persist"},{c:"适应",p:"shì yìng",e:"Adapt"},
    {c:"模仿",p:"mó fǎng",e:"Imitate"},{c:"假装",p:"jiǎ zhuāng",e:"Pretend"},
    // Abstract nouns
    {c:"印象",p:"yìn xiàng",e:"Impression"},{c:"想象",p:"xiǎng xiàng",e:"Imagination"},
    {c:"创意",p:"chuàng yì",e:"Creativity"},{c:"灵感",p:"líng gǎn",e:"Inspiration"},
    {c:"记忆",p:"jì yì",e:"Memory"},{c:"注意力",p:"zhù yì lì",e:"Attention"},
    {c:"能力",p:"néng lì",e:"Ability"},{c:"技能",p:"jì néng",e:"Skill"},
    {c:"天赋",p:"tiān fù",e:"Talent"},{c:"优点",p:"yōu diǎn",e:"Advantage"},
    {c:"缺点",p:"quē diǎn",e:"Disadvantage"},{c:"区别",p:"qū bié",e:"Difference"},
    {c:"相同",p:"xiāng tóng",e:"Same"},{c:"不同",p:"bù tóng",e:"Different"},
    {c:"简单",p:"jiǎn dān",e:"Simple"},{c:"复杂",p:"fù zá",e:"Complex"},
    {c:"普通",p:"pǔ tōng",e:"Ordinary"},{c:"特殊",p:"tè shū",e:"Special"},
    // Time expressions
    {c:"刚才",p:"gāng cái",e:"Just now"},{c:"立刻",p:"lì kè",e:"Right away"},
    {c:"将来",p:"jiāng lái",e:"Future"},{c:"过去",p:"guò qù",e:"Past"},
    {c:"永远",p:"yǒng yuǎn",e:"Forever"},{c:"暂时",p:"zàn shí",e:"Temporarily"},
    {c:"经常",p:"jīng cháng",e:"Frequently"},{c:"偶尔",p:"ǒu ěr",e:"Occasionally"},
    {c:"终于",p:"zhōng yú",e:"Finally"},{c:"逐渐",p:"zhú jiàn",e:"Gradually"},
    // Emotions & personality deeper
    {c:"自信",p:"zì xìn",e:"Confident"},{c:"害羞",p:"hài xiū",e:"Shy"},
    {c:"固执",p:"gù zhí",e:"Stubborn"},{c:"大方",p:"dà fāng",e:"Generous"},
    {c:"小气",p:"xiǎo qì",e:"Stingy"},{c:"乐观",p:"lè guān",e:"Optimistic"},
    {c:"悲观",p:"bēi guān",e:"Pessimistic"},{c:"冷静",p:"lěng jìng",e:"Calm"},
    {c:"激动",p:"jī dòng",e:"Agitated"},{c:"感激",p:"gǎn jī",e:"Grateful"},
    // Society & relationships
    {c:"尊敬",p:"zūn jìng",e:"Respect (verb)"},{c:"信任",p:"xìn rèn",e:"Trust"},
    {c:"背叛",p:"bèi pàn",e:"Betray"},{c:"忠诚",p:"zhōng chéng",e:"Loyal"},
    {c:"友谊",p:"yǒu yì",e:"Friendship"},{c:"爱情",p:"ài qíng",e:"Romantic love"},
    {c:"亲情",p:"qīn qíng",e:"Family love"},{c:"婚礼",p:"hūn lǐ",e:"Wedding"},
    {c:"葬礼",p:"zàng lǐ",e:"Funeral"},{c:"庆祝",p:"qìng zhù",e:"Celebrate"},
    // Law & order
    {c:"警察局",p:"jǐng chá jú",e:"Police station"},
    {c:"消防员",p:"xiāo fáng yuán",e:"Firefighter"},
    {c:"法院",p:"fǎ yuàn",e:"Court"},{c:"犯罪",p:"fàn zuì",e:"Crime"},
    {c:"证据",p:"zhèng jù",e:"Evidence"},{c:"审判",p:"shěn pàn",e:"Trial"},
    // Education deeper
    {c:"毕业",p:"bì yè",e:"Graduate"},{c:"学位",p:"xué wèi",e:"Degree"},
    {c:"奖学金",p:"jiǎng xué jīn",e:"Scholarship"},
    {c:"论文",p:"lùn wén",e:"Thesis"},{c:"专业",p:"zhuān yè",e:"Major/Specialty"},
    {c:"课程",p:"kè chéng",e:"Course"},{c:"学期",p:"xué qī",e:"Semester"},
    {c:"寒假",p:"hán jià",e:"Winter break"},{c:"暑假",p:"shǔ jià",e:"Summer break"},
    // Media & arts
    {c:"摄影",p:"shè yǐng",e:"Photography"},{c:"展览",p:"zhǎn lǎn",e:"Exhibition"},
    {c:"画廊",p:"huà láng",e:"Gallery"},{c:"音乐会",p:"yīn yuè huì",e:"Concert"},
    {c:"交响乐",p:"jiāo xiǎng yuè",e:"Symphony"},
    {c:"乐器",p:"yuè qì",e:"Musical instrument"},
    {c:"舞台",p:"wǔ tái",e:"Stage"},{c:"观众席",p:"guān zhòng xí",e:"Audience seats"},
    {c:"门票",p:"mén piào",e:"Ticket"},{c:"售票处",p:"shòu piào chù",e:"Ticket office"},
    // Health & medicine
    {c:"手术",p:"shǒu shù",e:"Surgery"},{c:"治疗",p:"zhì liáo",e:"Treatment"},
    {c:"诊断",p:"zhěn duàn",e:"Diagnosis"},{c:"处方",p:"chǔ fāng",e:"Prescription"},
    {c:"疫苗",p:"yì miáo",e:"Vaccine"},{c:"过敏",p:"guò mǐn",e:"Allergy"},
    {c:"营养",p:"yíng yǎng",e:"Nutrition"},{c:"维生素",p:"wéi shēng sù",e:"Vitamin"},
    {c:"锻炼",p:"duàn liàn",e:"Work out"},{c:"减肥",p:"jiǎn féi",e:"Lose weight"},
    // Numbers & math
    {c:"加",p:"jiā",e:"Add"},{c:"减",p:"jiǎn",e:"Subtract"},
    {c:"乘",p:"chéng",e:"Multiply"},{c:"除",p:"chú",e:"Divide"},
    {c:"等于",p:"děng yú",e:"Equals"},{c:"分数",p:"fēn shù",e:"Fraction/Score"},
    {c:"百分之",p:"bǎi fēn zhī",e:"Percent"},{c:"倍",p:"bèi",e:"Times (multiplier)"},
    {c:"三角形",p:"sān jiǎo xíng",e:"Triangle"},{c:"正方形",p:"zhèng fāng xíng",e:"Square"},
    {c:"长方形",p:"cháng fāng xíng",e:"Rectangle"},{c:"圆形",p:"yuán xíng",e:"Circle"},
  ],
  8: [
    {c:"经济",p:"jīng jì",e:"Economy"},{c:"政治",p:"zhèng zhì",e:"Politics"},
    {c:"社会",p:"shè huì",e:"Society"},{c:"文化",p:"wén huà",e:"Culture"},
    {c:"技术",p:"jì shù",e:"Technology"},{c:"传统",p:"chuán tǒng",e:"Traditional"},
    {c:"现代",p:"xiàn dài",e:"Modern"},{c:"国际",p:"guó jì",e:"International"},
    {c:"交流",p:"jiāo liú",e:"Exchange"},{c:"合作",p:"hé zuò",e:"Cooperate"},
    {c:"竞争",p:"jìng zhēng",e:"Competition"},{c:"影响",p:"yǐng xiǎng",e:"Influence"},
    {c:"责任",p:"zé rèn",e:"Responsibility"},{c:"经验",p:"jīng yàn",e:"Experience"},
    {c:"机会",p:"jī huì",e:"Opportunity"},{c:"困难",p:"kùn nán",e:"Difficulty"},
    {c:"问题",p:"wèn tí",e:"Problem"},{c:"答案",p:"dá àn",e:"Answer"},
    {c:"方法",p:"fāng fǎ",e:"Method"},{c:"原因",p:"yuán yīn",e:"Reason"},
    {c:"结果",p:"jié guǒ",e:"Result"},{c:"关系",p:"guān xi",e:"Relationship"},
    {c:"情况",p:"qíng kuàng",e:"Situation"},{c:"条件",p:"tiáo jiàn",e:"Condition"},
    {c:"目标",p:"mù biāo",e:"Goal"},{c:"意见",p:"yì jiàn",e:"Opinion"},
    {c:"建议",p:"jiàn yì",e:"Suggestion"},{c:"态度",p:"tài du",e:"Attitude"},
    {c:"精神",p:"jīng shén",e:"Spirit"},{c:"感觉",p:"gǎn jué",e:"Feel"},
    {c:"思想",p:"sī xiǎng",e:"Thought"},{c:"梦想",p:"mèng xiǎng",e:"Dream"},
    {c:"幸福",p:"xìng fú",e:"Happiness"},{c:"自由",p:"zì yóu",e:"Freedom"},
    {c:"和平",p:"hé píng",e:"Peace",i:"peace-symbol"},
    {c:"尊重",p:"zūn zhòng",e:"Respect"},{c:"诚实",p:"chéng shí",e:"Honest"},
    {c:"勤劳",p:"qín láo",e:"Diligent"},{c:"耐心",p:"nài xīn",e:"Patient"},
    {c:"谦虚",p:"qiān xū",e:"Humble"},{c:"勇气",p:"yǒng qì",e:"Courage"},
    {c:"智慧",p:"zhì huì",e:"Wisdom"},{c:"知识",p:"zhī shi",e:"Knowledge"},
    {c:"教育",p:"jiào yù",e:"Education"},{c:"研究",p:"yán jiū",e:"Research"},
    {c:"实验",p:"shí yàn",e:"Experiment"},{c:"发明",p:"fā míng",e:"Invent"},
    {c:"创造",p:"chuàng zào",e:"Create"},{c:"设计",p:"shè jì",e:"Design"},
    {c:"管理",p:"guǎn lǐ",e:"Manage"},{c:"组织",p:"zǔ zhī",e:"Organize"},
    {c:"领导",p:"lǐng dǎo",e:"Lead"},{c:"团队",p:"tuán duì",e:"Team"},
    {c:"公司",p:"gōng sī",e:"Company"},{c:"工厂",p:"gōng chǎng",e:"Factory"},
    {c:"产品",p:"chǎn pǐn",e:"Product"},{c:"服务",p:"fú wù",e:"Service"},
    {c:"质量",p:"zhì liàng",e:"Quality"},{c:"价格",p:"jià gé",e:"Price"},
    {c:"广告",p:"guǎng gào",e:"Advertisement"},{c:"品牌",p:"pǐn pái",e:"Brand"},
    {c:"客户",p:"kè hù",e:"Customer"},{c:"合同",p:"hé tong",e:"Contract"},
    {c:"法律",p:"fǎ lǜ",e:"Law"},{c:"规则",p:"guī zé",e:"Rule"},
    {c:"权利",p:"quán lì",e:"Right (legal)"},{c:"义务",p:"yì wù",e:"Duty"},
    {c:"自然",p:"zì rán",e:"Nature"},{c:"空气",p:"kōng qì",e:"Air"},
    {c:"污染",p:"wū rǎn",e:"Pollution"},{c:"能源",p:"néng yuán",e:"Energy"},
    {c:"资源",p:"zī yuán",e:"Resource"},{c:"回收",p:"huí shōu",e:"Recycle"},
    {c:"节约",p:"jié yuē",e:"Save/Conserve"},{c:"太空",p:"tài kōng",e:"Space"},
    {c:"宇宙",p:"yǔ zhòu",e:"Universe"},{c:"星球",p:"xīng qiú",e:"Planet"},
    {c:"科技",p:"kē jì",e:"Tech"},{c:"人工智能",p:"rén gōng zhì néng",e:"AI"},
    {c:"机器人",p:"jī qì rén",e:"Robot"},{c:"程序",p:"chéng xù",e:"Program"},
    {c:"数据",p:"shù jù",e:"Data"},{c:"系统",p:"xì tǒng",e:"System"},
    {c:"网站",p:"wǎng zhàn",e:"Website"},{c:"软件",p:"ruǎn jiàn",e:"Software"},
    {c:"硬件",p:"yìng jiàn",e:"Hardware"},{c:"屏幕",p:"píng mù",e:"Screen"},
    {c:"键盘",p:"jiàn pán",e:"Keyboard"},{c:"鼠标",p:"shǔ biāo",e:"Mouse (computer)"},
    {c:"打印",p:"dǎ yìn",e:"Print"},{c:"复制",p:"fù zhì",e:"Copy"},
    {c:"粘贴",p:"zhān tiē",e:"Paste"},{c:"删除",p:"shān chú",e:"Delete"},
    {c:"保存",p:"bǎo cún",e:"Save"},{c:"下载",p:"xià zǎi",e:"Download"},
    {c:"上传",p:"shàng chuán",e:"Upload"},{c:"搜索",p:"sōu suǒ",e:"Search"},
    {c:"连接",p:"lián jiē",e:"Connect"},{c:"断开",p:"duàn kāi",e:"Disconnect"},
    {c:"充电",p:"chōng diàn",e:"Charge"},{c:"电池",p:"diàn chí",e:"Battery"},
    {c:"信号",p:"xìn hào",e:"Signal"},{c:"频道",p:"pín dào",e:"Channel"},
    {c:"观众",p:"guān zhòng",e:"Audience"},{c:"粉丝",p:"fěn sī",e:"Fan/Follower"},
    {c:"演员",p:"yǎn yuán",e:"Actor"},{c:"导演",p:"dǎo yǎn",e:"Director"},
    {c:"作家",p:"zuò jiā",e:"Writer"},{c:"画家",p:"huà jiā",e:"Painter"},
    {c:"歌手",p:"gē shǒu",e:"Singer"},{c:"律师",p:"lǜ shī",e:"Lawyer"},
    {c:"工程师",p:"gōng chéng shī",e:"Engineer"},{c:"会计",p:"kuài jì",e:"Accountant"},
    {c:"记者",p:"jì zhě",e:"Reporter"},{c:"厨师",p:"chú shī",e:"Chef"},
    {c:"司机",p:"sī jī",e:"Driver"},{c:"农民",p:"nóng mín",e:"Farmer"},
    {c:"军人",p:"jūn rén",e:"Soldier"},{c:"运动员",p:"yùn dòng yuán",e:"Athlete"},
    {c:"志愿者",p:"zhì yuàn zhě",e:"Volunteer"},{c:"邻居",p:"lín jū",e:"Neighbor"},
    {c:"亲戚",p:"qīn qi",e:"Relative"},{c:"丈夫",p:"zhàng fu",e:"Husband"},
    {c:"妻子",p:"qī zi",e:"Wife"},{c:"儿子",p:"ér zi",e:"Son"},
    {c:"女儿",p:"nǚ ér",e:"Daughter"},{c:"孙子",p:"sūn zi",e:"Grandson"},
    {c:"婴儿",p:"yīng ér",e:"Baby"},{c:"青年",p:"qīng nián",e:"Youth"},
    {c:"成年",p:"chéng nián",e:"Adult"},{c:"老人",p:"lǎo rén",e:"Elder"},
    {c:"性格",p:"xìng gé",e:"Personality"},{c:"习惯",p:"xí guàn",e:"Habit"},
    {c:"爱好",p:"ài hào",e:"Hobby"},{c:"兴趣",p:"xìng qù",e:"Interest"},
    {c:"理想",p:"lǐ xiǎng",e:"Ideal"},{c:"信念",p:"xìn niàn",e:"Belief"},
    {c:"道德",p:"dào dé",e:"Morality"},{c:"良心",p:"liáng xīn",e:"Conscience"},
    {c:"公平",p:"gōng píng",e:"Fair"},{c:"正义",p:"zhèng yì",e:"Justice"},
    {c:"民主",p:"mín zhǔ",e:"Democracy"},{c:"选举",p:"xuǎn jǔ",e:"Election"},
    {c:"政府",p:"zhèng fǔ",e:"Government"},{c:"总统",p:"zǒng tǒng",e:"President"},
    {c:"首都",p:"shǒu dū",e:"Capital city"},{c:"省",p:"shěng",e:"Province"},
    {c:"城市",p:"chéng shì",e:"City"},{c:"农村",p:"nóng cūn",e:"Countryside"},
    {c:"人口",p:"rén kǒu",e:"Population"},{c:"面积",p:"miàn jī",e:"Area"},
    {c:"距离",p:"jù lí",e:"Distance"},{c:"速度",p:"sù dù",e:"Speed"},
    {c:"重量",p:"zhòng liàng",e:"Weight"},{c:"高度",p:"gāo dù",e:"Height/Altitude"},
    {c:"深度",p:"shēn dù",e:"Depth"},{c:"宽度",p:"kuān dù",e:"Width"},
    {c:"材料",p:"cái liào",e:"Material"},{c:"工具",p:"gōng jù",e:"Tool"},
    {c:"机器",p:"jī qì",e:"Machine"},{c:"设备",p:"shè bèi",e:"Equipment"},
    {c:"交通",p:"jiāo tōng",e:"Traffic"},{c:"信号灯",p:"xìn hào dēng",e:"Traffic light"},
    {c:"高速公路",p:"gāo sù gōng lù",e:"Highway"},{c:"停车场",p:"tíng chē chǎng",e:"Parking lot"},
    {c:"加油站",p:"jiā yóu zhàn",e:"Gas station"},{c:"红绿灯",p:"hóng lǜ dēng",e:"Traffic light"},
    {c:"地图",p:"dì tú",e:"Map"},{c:"方向",p:"fāng xiàng",e:"Direction"},
    {c:"左转",p:"zuǒ zhuǎn",e:"Turn left"},{c:"右转",p:"yòu zhuǎn",e:"Turn right"},
    {c:"直走",p:"zhí zǒu",e:"Go straight"},{c:"到达",p:"dào dá",e:"Arrive"},
    {c:"出发",p:"chū fā",e:"Depart"},{c:"旅行",p:"lǚ xíng",e:"Travel"},
    {c:"旅游",p:"lǚ yóu",e:"Tourism"},{c:"景点",p:"jǐng diǎn",e:"Scenic spot"},
    {c:"风景",p:"fēng jǐng",e:"Scenery"},{c:"纪念品",p:"jì niàn pǐn",e:"Souvenir"},
    {c:"预订",p:"yù dìng",e:"Reserve/Book"},{c:"退房",p:"tuì fáng",e:"Check out"},
    {c:"登机",p:"dēng jī",e:"Board (plane)"},{c:"起飞",p:"qǐ fēi",e:"Take off"},
    {c:"降落",p:"jiàng luò",e:"Land"},{c:"航班",p:"háng bān",e:"Flight"},
    {c:"乘客",p:"chéng kè",e:"Passenger"},{c:"座位",p:"zuò wèi",e:"Seat"},
    {c:"安全带",p:"ān quán dài",e:"Seatbelt"},{c:"行李箱",p:"xíng li xiāng",e:"Suitcase"},
    // More professions & society
    {c:"科学家",p:"kē xué jiā",e:"Scientist"},{c:"哲学家",p:"zhé xué jiā",e:"Philosopher"},
    {c:"音乐家",p:"yīn yuè jiā",e:"Musician"},{c:"翻译家",p:"fān yì jiā",e:"Translator"},
    {c:"建筑师",p:"jiàn zhù shī",e:"Architect"},{c:"药剂师",p:"yào jì shī",e:"Pharmacist"},
    {c:"心理学",p:"xīn lǐ xué",e:"Psychology"},{c:"哲学",p:"zhé xué",e:"Philosophy"},
    {c:"物理",p:"wù lǐ",e:"Physics"},{c:"化学",p:"huà xué",e:"Chemistry"},
    {c:"生物",p:"shēng wù",e:"Biology"},{c:"天文",p:"tiān wén",e:"Astronomy"},
    {c:"数学家",p:"shù xué jiā",e:"Mathematician"},{c:"实验室",p:"shí yàn shì",e:"Laboratory"},
    {c:"理论",p:"lǐ lùn",e:"Theory"},{c:"证明",p:"zhèng míng",e:"Prove"},
    {c:"假设",p:"jiǎ shè",e:"Hypothesis"},{c:"观察",p:"guān chá",e:"Observe"},
    {c:"分析",p:"fēn xī",e:"Analyze"},{c:"总结",p:"zǒng jié",e:"Summarize"},
    {c:"报告",p:"bào gào",e:"Report"},{c:"演讲",p:"yǎn jiǎng",e:"Speech"},
    {c:"辩论",p:"biàn lùn",e:"Debate"},{c:"主题",p:"zhǔ tí",e:"Theme/Topic"},
    // Economics & business
    {c:"投资",p:"tóu zī",e:"Invest"},{c:"利润",p:"lì rùn",e:"Profit"},
    {c:"亏损",p:"kuī sǔn",e:"Loss"},{c:"预算",p:"yù suàn",e:"Budget"},
    {c:"工资",p:"gōng zī",e:"Salary"},{c:"税",p:"shuì",e:"Tax"},
    {c:"贸易",p:"mào yì",e:"Trade"},{c:"进口",p:"jìn kǒu",e:"Import"},
    {c:"出口",p:"chū kǒu",e:"Export"},{c:"货币",p:"huò bì",e:"Currency"},
    {c:"汇率",p:"huì lǜ",e:"Exchange rate"},{c:"股票",p:"gǔ piào",e:"Stock"},
    {c:"保险",p:"bǎo xiǎn",e:"Insurance"},{c:"贷款",p:"dài kuǎn",e:"Loan"},
    {c:"利息",p:"lì xī",e:"Interest"},{c:"存款",p:"cún kuǎn",e:"Savings"},
    // Arts & literature
    {c:"小说",p:"xiǎo shuō",e:"Novel"},{c:"散文",p:"sǎn wén",e:"Prose"},
    {c:"戏剧",p:"xì jù",e:"Drama"},{c:"悲剧",p:"bēi jù",e:"Tragedy"},
    {c:"喜剧",p:"xǐ jù",e:"Comedy"},{c:"浪漫",p:"làng màn",e:"Romantic"},
    {c:"幽默",p:"yōu mò",e:"Humorous"},{c:"讽刺",p:"fěng cì",e:"Satire"},
    {c:"象征",p:"xiàng zhēng",e:"Symbolize"},{c:"比喻",p:"bǐ yù",e:"Metaphor"},
    {c:"描写",p:"miáo xiě",e:"Describe"},{c:"叙述",p:"xù shù",e:"Narrate"},
    {c:"书法",p:"shū fǎ",e:"Calligraphy"},{c:"国画",p:"guó huà",e:"Chinese painting"},
    {c:"雕塑",p:"diāo sù",e:"Sculpture"},{c:"陶瓷",p:"táo cí",e:"Ceramics"},
    // Environment & science
    {c:"气候",p:"qì hòu",e:"Climate"},{c:"全球变暖",p:"quán qiú biàn nuǎn",e:"Global warming"},
    {c:"温室效应",p:"wēn shì xiào yìng",e:"Greenhouse effect"},
    {c:"碳排放",p:"tàn pái fàng",e:"Carbon emissions"},
    {c:"可持续",p:"kě chí xù",e:"Sustainable"},{c:"生态",p:"shēng tài",e:"Ecology"},
    {c:"物种",p:"wù zhǒng",e:"Species"},{c:"灭绝",p:"miè jué",e:"Extinction"},
    {c:"濒危",p:"bīn wēi",e:"Endangered"},{c:"森林",p:"sēn lín",e:"Forest"},
    {c:"热带雨林",p:"rè dài yǔ lín",e:"Tropical rainforest"},
    {c:"珊瑚礁",p:"shān hú jiāo",e:"Coral reef"},
    {c:"冰川",p:"bīng chuān",e:"Glacier"},{c:"北极",p:"běi jí",e:"North Pole"},
    {c:"南极",p:"nán jí",e:"South Pole"},{c:"赤道",p:"chì dào",e:"Equator"},
    // Philosophy & abstract
    {c:"存在",p:"cún zài",e:"Exist"},{c:"本质",p:"běn zhì",e:"Essence"},
    {c:"现象",p:"xiàn xiàng",e:"Phenomenon"},{c:"规律",p:"guī lǜ",e:"Pattern/Law"},
    {c:"矛盾",p:"máo dùn",e:"Contradiction"},{c:"和谐",p:"hé xié",e:"Harmony"},
    {c:"平衡",p:"píng héng",e:"Balance"},{c:"趋势",p:"qū shì",e:"Trend"},
    {c:"改革",p:"gǎi gé",e:"Reform"},{c:"革命",p:"gé mìng",e:"Revolution"},
    {c:"独立",p:"dú lì",e:"Independent"},{c:"统一",p:"tǒng yī",e:"Unify"},
    {c:"联合",p:"lián hé",e:"Unite"},{c:"分裂",p:"fēn liè",e:"Split"},
    {c:"冲突",p:"chōng tū",e:"Conflict"},{c:"谈判",p:"tán pàn",e:"Negotiate"},
    {c:"妥协",p:"tuǒ xié",e:"Compromise"},{c:"协议",p:"xié yì",e:"Agreement"},
    {c:"条约",p:"tiáo yuē",e:"Treaty"},{c:"宣布",p:"xuān bù",e:"Announce"},
    {c:"公布",p:"gōng bù",e:"Publish/Release"},{c:"禁止",p:"jìn zhǐ",e:"Prohibit"},
    {c:"允许",p:"yǔn xǔ",e:"Allow"},{c:"要求",p:"yāo qiú",e:"Demand"},
    {c:"建设",p:"jiàn shè",e:"Construction"},{c:"维修",p:"wéi xiū",e:"Maintenance"},
    {c:"改善",p:"gǎi shàn",e:"Improve"},{c:"恢复",p:"huī fù",e:"Restore"},
    {c:"推广",p:"tuī guǎng",e:"Promote"},{c:"普及",p:"pǔ jí",e:"Popularize"},
  ],
};

// Build flat lookup
const ALL_WORDS = {};
for (const level in WORD_BANK) {
  for (const w of WORD_BANK[level]) {
    ALL_WORDS[w.c] = w;
  }
}

// Map levels to age/maxLevel settings
const LEVEL_CAP = { "3-5": 3, "6-8": 5, "9-11": 7, "12+": 8 };
