// PandaFlip Word Bank - Comprehensive Chinese vocabulary
// Each word: { c: chinese, p: pinyin, e: english, i: icon (optional) }
// Levels 1-8, ~2000+ words

const WORD_BANK = {
  1: [
    {c:"一",p:"yī",e:"One",i:"keycap-1"},{c:"二",p:"èr",e:"Two",i:"victory-hand"},
    {c:"三",p:"sān",e:"Three",i:"keycap-3"},{c:"四",p:"sì",e:"Four"},
    {c:"五",p:"wǔ",e:"Five",i:"raised-hand"},{c:"六",p:"liù",e:"Six",i:"game-die"},
    {c:"七",p:"qī",e:"Seven"},{c:"八",p:"bā",e:"Eight"},
    {c:"九",p:"jiǔ",e:"Nine"},{c:"十",p:"shí",e:"Ten"},
    {c:"人",p:"rén",e:"Person",i:"person-standing"},{c:"大",p:"dà",e:"Big",i:"elephant"},
    {c:"小",p:"xiǎo",e:"Small",i:"ant"},{c:"口",p:"kǒu",e:"Mouth",i:"mouth"},
    {c:"手",p:"shǒu",e:"Hand",i:"waving-hand"},{c:"山",p:"shān",e:"Mountain",i:"mountain"},
    {c:"水",p:"shuǐ",e:"Water",i:"droplet"},{c:"火",p:"huǒ",e:"Fire",i:"fire"},
    {c:"天",p:"tiān",e:"Sky",i:"sun-behind-cloud"},{c:"日",p:"rì",e:"Day",i:"sun"},
    {c:"月",p:"yuè",e:"Moon",i:"crescent-moon"},{c:"木",p:"mù",e:"Wood"},
    {c:"土",p:"tǔ",e:"Earth"},{c:"石",p:"shí",e:"Stone"},
    {c:"田",p:"tián",e:"Field"},{c:"目",p:"mù",e:"Eye",i:"eyes"},
    {c:"耳",p:"ěr",e:"Ear",i:"ear"},{c:"心",p:"xīn",e:"Heart",i:"red-heart"},
    {c:"门",p:"mén",e:"Door"},{c:"雨",p:"yǔ",e:"Rain",i:"cloud-with-rain"},
    {c:"上",p:"shàng",e:"Up"},{c:"下",p:"xià",e:"Down"},
    {c:"中",p:"zhōng",e:"Middle"},{c:"头",p:"tóu",e:"Head"},
    {c:"足",p:"zú",e:"Foot"},{c:"女",p:"nǚ",e:"Woman"},
    {c:"男",p:"nán",e:"Man"},{c:"子",p:"zǐ",e:"Child"},
  ],
  2: [
    {c:"猫",p:"māo",e:"Cat",i:"cat-face"},{c:"狗",p:"gǒu",e:"Dog",i:"dog-face"},
    {c:"鱼",p:"yú",e:"Fish",i:"fish"},{c:"鸟",p:"niǎo",e:"Bird",i:"bird"},
    {c:"马",p:"mǎ",e:"Horse",i:"horse-face"},{c:"牛",p:"niú",e:"Cow",i:"cow-face"},
    {c:"羊",p:"yáng",e:"Sheep"},{c:"猪",p:"zhū",e:"Pig",i:"pig-face"},
    {c:"兔",p:"tù",e:"Rabbit",i:"rabbit-face"},{c:"虎",p:"hǔ",e:"Tiger",i:"tiger-face"},
    {c:"龙",p:"lóng",e:"Dragon",i:"dragon"},{c:"蛇",p:"shé",e:"Snake",i:"snake"},
    {c:"鸡",p:"jī",e:"Chicken",i:"rooster"},{c:"鸭",p:"yā",e:"Duck"},
    {c:"鹅",p:"é",e:"Goose"},{c:"虫",p:"chóng",e:"Bug",i:"bug"},
    {c:"红",p:"hóng",e:"Red",i:"red-heart"},{c:"蓝",p:"lán",e:"Blue",i:"blue-heart"},
    {c:"白",p:"bái",e:"White"},{c:"黑",p:"hēi",e:"Black"},
    {c:"绿",p:"lǜ",e:"Green",i:"green-heart"},{c:"黄",p:"huáng",e:"Yellow",i:"yellow-heart"},
    {c:"花",p:"huā",e:"Flower",i:"cherry-blossom"},{c:"树",p:"shù",e:"Tree",i:"deciduous-tree"},
    {c:"草",p:"cǎo",e:"Grass"},{c:"河",p:"hé",e:"River"},
    {c:"海",p:"hǎi",e:"Sea"},{c:"湖",p:"hú",e:"Lake"},
    {c:"风",p:"fēng",e:"Wind",i:"wind-face"},{c:"雪",p:"xuě",e:"Snow",i:"snowflake"},
    {c:"云",p:"yún",e:"Cloud",i:"cloud"},{c:"星",p:"xīng",e:"Star",i:"glowing-star"},
    {c:"冰",p:"bīng",e:"Ice"},{c:"竹",p:"zhú",e:"Bamboo"},
    {c:"金",p:"jīn",e:"Gold"},{c:"银",p:"yín",e:"Silver"},
    {c:"铁",p:"tiě",e:"Iron"},{c:"沙",p:"shā",e:"Sand"},
    {c:"岛",p:"dǎo",e:"Island"},{c:"森林",p:"sēn lín",e:"Forest"},
  ],
  3: [
    {c:"你好",p:"nǐ hǎo",e:"Hello",i:"waving-hand"},
    {c:"谢谢",p:"xiè xie",e:"Thank you",i:"folded-hands"},
    {c:"再见",p:"zài jiàn",e:"Goodbye"},{c:"对不起",p:"duì bu qǐ",e:"Sorry"},
    {c:"没关系",p:"méi guān xi",e:"It's okay"},{c:"请",p:"qǐng",e:"Please"},
    {c:"不客气",p:"bú kè qì",e:"You're welcome"},
    {c:"妈妈",p:"mā ma",e:"Mom",i:"woman"},{c:"爸爸",p:"bà ba",e:"Dad",i:"man"},
    {c:"哥哥",p:"gē ge",e:"Older brother"},{c:"姐姐",p:"jiě jie",e:"Older sister"},
    {c:"弟弟",p:"dì di",e:"Younger brother"},{c:"妹妹",p:"mèi mei",e:"Younger sister"},
    {c:"爷爷",p:"yé ye",e:"Grandpa (paternal)"},{c:"奶奶",p:"nǎi nai",e:"Grandma (paternal)"},
    {c:"外公",p:"wài gōng",e:"Grandpa (maternal)"},{c:"外婆",p:"wài pó",e:"Grandma (maternal)"},
    {c:"朋友",p:"péng yǒu",e:"Friend",i:"handshake"},
    {c:"太阳",p:"tài yáng",e:"Sun",i:"sun-with-face"},
    {c:"月亮",p:"yuè liang",e:"Moon",i:"crescent-moon"},
    {c:"星星",p:"xīng xing",e:"Star",i:"glowing-star"},
    {c:"苹果",p:"píng guǒ",e:"Apple",i:"red-apple"},
    {c:"香蕉",p:"xiāng jiāo",e:"Banana",i:"banana"},
    {c:"西瓜",p:"xī guā",e:"Watermelon",i:"watermelon"},
    {c:"牛奶",p:"niú nǎi",e:"Milk",i:"glass-of-milk"},
    {c:"米饭",p:"mǐ fàn",e:"Rice",i:"cooked-rice"},
    {c:"面包",p:"miàn bāo",e:"Bread",i:"bread"},
    {c:"鸡蛋",p:"jī dàn",e:"Egg",i:"egg"},
    {c:"水果",p:"shuǐ guǒ",e:"Fruit"},
    {c:"吃",p:"chī",e:"Eat",i:"fork-and-knife"},{c:"喝",p:"hē",e:"Drink",i:"cup-with-straw"},
    {c:"跑",p:"pǎo",e:"Run",i:"person-running"},{c:"走",p:"zǒu",e:"Walk",i:"person-walking"},
    {c:"看",p:"kàn",e:"Look",i:"eyes"},{c:"听",p:"tīng",e:"Listen",i:"ear"},
    {c:"说",p:"shuō",e:"Say"},{c:"读",p:"dú",e:"Read"},
    {c:"写",p:"xiě",e:"Write",i:"pencil"},{c:"来",p:"lái",e:"Come"},
    {c:"去",p:"qù",e:"Go"},{c:"坐",p:"zuò",e:"Sit"},
    {c:"站",p:"zhàn",e:"Stand"},{c:"笑",p:"xiào",e:"Laugh"},
    {c:"哭",p:"kū",e:"Cry"},{c:"睡",p:"shuì",e:"Sleep"},
    {c:"飞",p:"fēi",e:"Fly"},{c:"游",p:"yóu",e:"Swim"},
    {c:"唱",p:"chàng",e:"Sing"},{c:"跳",p:"tiào",e:"Jump"},
    {c:"打",p:"dǎ",e:"Hit"},{c:"拉",p:"lā",e:"Pull"},
    {c:"推",p:"tuī",e:"Push"},{c:"抱",p:"bào",e:"Hug"},
  ],
  4: [
    {c:"学校",p:"xué xiào",e:"School",i:"school"},
    {c:"老师",p:"lǎo shī",e:"Teacher",i:"woman-teacher"},
    {c:"学生",p:"xué shēng",e:"Student",i:"backpack"},
    {c:"同学",p:"tóng xué",e:"Classmate"},{c:"书",p:"shū",e:"Book",i:"open-book"},
    {c:"笔",p:"bǐ",e:"Pen",i:"pencil"},{c:"纸",p:"zhǐ",e:"Paper"},
    {c:"教室",p:"jiào shì",e:"Classroom"},{c:"作业",p:"zuò yè",e:"Homework"},
    {c:"考试",p:"kǎo shì",e:"Exam"},{c:"课",p:"kè",e:"Class/Lesson"},
    {c:"电话",p:"diàn huà",e:"Phone",i:"mobile-phone"},
    {c:"时间",p:"shí jiān",e:"Time",i:"alarm-clock"},
    {c:"今天",p:"jīn tiān",e:"Today",i:"calendar"},
    {c:"明天",p:"míng tiān",e:"Tomorrow",i:"sunrise"},
    {c:"昨天",p:"zuó tiān",e:"Yesterday"},{c:"早上",p:"zǎo shang",e:"Morning"},
    {c:"晚上",p:"wǎn shang",e:"Evening",i:"night-with-stars"},
    {c:"中午",p:"zhōng wǔ",e:"Noon"},{c:"下午",p:"xià wǔ",e:"Afternoon"},
    {c:"上午",p:"shàng wǔ",e:"Late morning"},{c:"现在",p:"xiàn zài",e:"Now"},
    {c:"小时",p:"xiǎo shí",e:"Hour"},{c:"分钟",p:"fēn zhōng",e:"Minute"},
    {c:"高兴",p:"gāo xìng",e:"Happy",i:"grinning-face-with-big-eyes"},
    {c:"快乐",p:"kuài lè",e:"Joyful",i:"partying-face"},
    {c:"难过",p:"nán guò",e:"Sad",i:"crying-face"},
    {c:"生气",p:"shēng qì",e:"Angry",i:"angry-face"},
    {c:"害怕",p:"hài pà",e:"Scared"},{c:"漂亮",p:"piào liang",e:"Pretty"},
    {c:"可爱",p:"kě ài",e:"Cute"},{c:"左",p:"zuǒ",e:"Left"},
    {c:"右",p:"yòu",e:"Right"},{c:"前",p:"qián",e:"Front"},
    {c:"后",p:"hòu",e:"Behind"},{c:"里",p:"lǐ",e:"Inside"},
    {c:"外",p:"wài",e:"Outside"},{c:"桌子",p:"zhuō zi",e:"Table"},
    {c:"椅子",p:"yǐ zi",e:"Chair"},{c:"床",p:"chuáng",e:"Bed"},
    {c:"灯",p:"dēng",e:"Light",i:"light-bulb"},{c:"窗",p:"chuāng",e:"Window"},
    {c:"筷子",p:"kuài zi",e:"Chopsticks",i:"chopsticks"},
    {c:"碗",p:"wǎn",e:"Bowl"},{c:"杯子",p:"bēi zi",e:"Cup"},
    {c:"医生",p:"yī shēng",e:"Doctor",i:"man-health-worker"},
    {c:"家",p:"jiā",e:"Home",i:"house"},{c:"房子",p:"fáng zi",e:"House"},
    {c:"房间",p:"fáng jiān",e:"Room"},{c:"厨房",p:"chú fáng",e:"Kitchen"},
    {c:"卧室",p:"wò shì",e:"Bedroom"},{c:"客厅",p:"kè tīng",e:"Living room"},
    {c:"卫生间",p:"wèi shēng jiān",e:"Bathroom"},
    {c:"钱",p:"qián",e:"Money"},{c:"东西",p:"dōng xi",e:"Thing/Stuff"},
    {c:"衣服",p:"yī fu",e:"Clothes",i:"shirt"},
    {c:"裤子",p:"kù zi",e:"Pants"},{c:"鞋子",p:"xié zi",e:"Shoes",i:"running-shoe"},
    {c:"帽子",p:"mào zi",e:"Hat"},{c:"裙子",p:"qún zi",e:"Skirt"},
  ],
  5: [
    {c:"飞机",p:"fēi jī",e:"Airplane",i:"airplane"},
    {c:"汽车",p:"qì chē",e:"Car",i:"automobile"},
    {c:"火车",p:"huǒ chē",e:"Train",i:"locomotive"},
    {c:"公共汽车",p:"gōng gòng qì chē",e:"Bus",i:"bus"},
    {c:"自行车",p:"zì xíng chē",e:"Bicycle",i:"bicycle"},
    {c:"地铁",p:"dì tiě",e:"Subway"},{c:"船",p:"chuán",e:"Boat",i:"sailboat"},
    {c:"出租车",p:"chū zū chē",e:"Taxi"},
    {c:"图书馆",p:"tú shū guǎn",e:"Library",i:"books"},
    {c:"动物园",p:"dòng wù yuán",e:"Zoo",i:"lion"},
    {c:"医院",p:"yī yuàn",e:"Hospital"},{c:"超市",p:"chāo shì",e:"Supermarket"},
    {c:"公园",p:"gōng yuán",e:"Park"},{c:"电影院",p:"diàn yǐng yuàn",e:"Cinema"},
    {c:"机场",p:"jī chǎng",e:"Airport"},{c:"银行",p:"yín háng",e:"Bank"},
    {c:"餐厅",p:"cān tīng",e:"Restaurant"},{c:"宾馆",p:"bīn guǎn",e:"Hotel"},
    {c:"商店",p:"shāng diàn",e:"Shop"},{c:"市场",p:"shì chǎng",e:"Market"},
    {c:"巧克力",p:"qiǎo kè lì",e:"Chocolate",i:"chocolate-bar"},
    {c:"冰淇淋",p:"bīng qí lín",e:"Ice cream"},
    {c:"饺子",p:"jiǎo zi",e:"Dumpling",i:"dumpling"},
    {c:"面条",p:"miàn tiáo",e:"Noodles",i:"steaming-bowl"},
    {c:"蛋糕",p:"dàn gāo",e:"Cake",i:"birthday-cake"},
    {c:"糖果",p:"táng guǒ",e:"Candy",i:"candy"},
    {c:"茶",p:"chá",e:"Tea",i:"teacup-without-handle"},
    {c:"咖啡",p:"kā fēi",e:"Coffee",i:"hot-beverage"},
    {c:"果汁",p:"guǒ zhī",e:"Juice"},{c:"可乐",p:"kě lè",e:"Cola"},
    {c:"牛肉",p:"niú ròu",e:"Beef"},{c:"猪肉",p:"zhū ròu",e:"Pork"},
    {c:"鸡肉",p:"jī ròu",e:"Chicken meat"},{c:"蔬菜",p:"shū cài",e:"Vegetables"},
    {c:"葡萄",p:"pú tao",e:"Grape",i:"grapes"},
    {c:"草莓",p:"cǎo méi",e:"Strawberry",i:"strawberry"},
    {c:"橙子",p:"chéng zi",e:"Orange",i:"tangerine"},
    {c:"桃子",p:"táo zi",e:"Peach",i:"peach"},{c:"梨",p:"lí",e:"Pear"},
    {c:"唱歌",p:"chàng gē",e:"Sing",i:"microphone"},
    {c:"跳舞",p:"tiào wǔ",e:"Dance",i:"woman-dancing"},
    {c:"画画",p:"huà huà",e:"Draw",i:"artist-palette"},
    {c:"游泳",p:"yóu yǒng",e:"Swim",i:"person-swimming"},
    {c:"踢足球",p:"tī zú qiú",e:"Play soccer",i:"soccer-ball"},
    {c:"打篮球",p:"dǎ lán qiú",e:"Play basketball",i:"basketball"},
    {c:"聪明",p:"cōng míng",e:"Smart",i:"brain"},
    {c:"勇敢",p:"yǒng gǎn",e:"Brave"},{c:"认真",p:"rèn zhēn",e:"Serious"},
    {c:"快",p:"kuài",e:"Fast"},{c:"慢",p:"màn",e:"Slow"},
    {c:"多",p:"duō",e:"Many"},{c:"少",p:"shǎo",e:"Few"},
    {c:"长",p:"cháng",e:"Long"},{c:"短",p:"duǎn",e:"Short"},
    {c:"高",p:"gāo",e:"Tall"},{c:"矮",p:"ǎi",e:"Short (height)"},
    {c:"胖",p:"pàng",e:"Fat"},{c:"瘦",p:"shòu",e:"Thin"},
    {c:"新",p:"xīn",e:"New"},{c:"旧",p:"jiù",e:"Old (things)"},
    {c:"冷",p:"lěng",e:"Cold"},{c:"热",p:"rè",e:"Hot"},
    {c:"好",p:"hǎo",e:"Good"},{c:"坏",p:"huài",e:"Bad"},
    {c:"对",p:"duì",e:"Correct"},{c:"错",p:"cuò",e:"Wrong"},
    {c:"远",p:"yuǎn",e:"Far"},{c:"近",p:"jìn",e:"Near"},
    {c:"轻",p:"qīng",e:"Light (weight)"},{c:"重",p:"zhòng",e:"Heavy"},
    {c:"干净",p:"gān jìng",e:"Clean"},{c:"脏",p:"zāng",e:"Dirty"},
    {c:"容易",p:"róng yì",e:"Easy"},{c:"难",p:"nán",e:"Difficult"},
    {c:"便宜",p:"pián yi",e:"Cheap"},{c:"贵",p:"guì",e:"Expensive"},
    {c:"忙",p:"máng",e:"Busy"},{c:"累",p:"lèi",e:"Tired"},
    {c:"饿",p:"è",e:"Hungry"},{c:"渴",p:"kě",e:"Thirsty"},
  ],
  6: [
    {c:"电脑",p:"diàn nǎo",e:"Computer",i:"laptop"},
    {c:"电视",p:"diàn shì",e:"TV",i:"television"},
    {c:"手机",p:"shǒu jī",e:"Cell phone",i:"mobile-phone"},
    {c:"音乐",p:"yīn yuè",e:"Music",i:"musical-notes"},
    {c:"钢琴",p:"gāng qín",e:"Piano",i:"musical-keyboard"},
    {c:"恐龙",p:"kǒng lóng",e:"Dinosaur",i:"t-rex"},
    {c:"蝴蝶",p:"hú dié",e:"Butterfly",i:"butterfly"},
    {c:"彩虹",p:"cǎi hóng",e:"Rainbow",i:"rainbow"},
    {c:"眼睛",p:"yǎn jīng",e:"Eyes",i:"eyes"},
    {c:"鼻子",p:"bí zi",e:"Nose"},{c:"嘴巴",p:"zuǐ ba",e:"Mouth"},
    {c:"牙齿",p:"yá chǐ",e:"Teeth"},{c:"头发",p:"tóu fa",e:"Hair"},
    {c:"手指",p:"shǒu zhǐ",e:"Finger"},{c:"脚",p:"jiǎo",e:"Foot"},
    {c:"腿",p:"tuǐ",e:"Leg"},{c:"肚子",p:"dù zi",e:"Belly"},
    {c:"脸",p:"liǎn",e:"Face"},{c:"背",p:"bèi",e:"Back"},
    {c:"肩膀",p:"jiān bǎng",e:"Shoulder"},{c:"膝盖",p:"xī gài",e:"Knee"},
    {c:"天气",p:"tiān qì",e:"Weather"},{c:"下雨",p:"xià yǔ",e:"Raining"},
    {c:"下雪",p:"xià xuě",e:"Snowing"},{c:"春天",p:"chūn tiān",e:"Spring"},
    {c:"夏天",p:"xià tiān",e:"Summer",i:"sun"},
    {c:"秋天",p:"qiū tiān",e:"Autumn",i:"fallen-leaf"},
    {c:"冬天",p:"dōng tiān",e:"Winter"},{c:"温度",p:"wēn dù",e:"Temperature"},
    {c:"知道",p:"zhī dào",e:"Know"},{c:"喜欢",p:"xǐ huān",e:"Like"},
    {c:"可以",p:"kě yǐ",e:"Can"},{c:"应该",p:"yīng gāi",e:"Should"},
    {c:"需要",p:"xū yào",e:"Need"},{c:"想",p:"xiǎng",e:"Think/Want"},
    {c:"做",p:"zuò",e:"Do/Make"},{c:"给",p:"gěi",e:"Give"},
    {c:"买",p:"mǎi",e:"Buy"},{c:"卖",p:"mài",e:"Sell"},
    {c:"开",p:"kāi",e:"Open"},{c:"关",p:"guān",e:"Close"},
    {c:"穿",p:"chuān",e:"Wear"},{c:"洗",p:"xǐ",e:"Wash"},
    {c:"玩",p:"wán",e:"Play"},{c:"学",p:"xué",e:"Study"},
    {c:"教",p:"jiāo",e:"Teach"},{c:"帮",p:"bāng",e:"Help"},
    {c:"找",p:"zhǎo",e:"Find"},{c:"用",p:"yòng",e:"Use"},
    {c:"拿",p:"ná",e:"Take"},{c:"放",p:"fàng",e:"Put"},
    {c:"送",p:"sòng",e:"Send/Give"},{c:"住",p:"zhù",e:"Live"},
    {c:"工作",p:"gōng zuò",e:"Work"},{c:"休息",p:"xiū xi",e:"Rest"},
    {c:"等",p:"děng",e:"Wait"},{c:"回",p:"huí",e:"Return"},
    {c:"问",p:"wèn",e:"Ask"},{c:"答",p:"dá",e:"Answer"},
    {c:"试",p:"shì",e:"Try"},{c:"让",p:"ràng",e:"Let/Allow"},
    {c:"带",p:"dài",e:"Bring"},{c:"换",p:"huàn",e:"Change/Exchange"},
    {c:"修",p:"xiū",e:"Fix"},{c:"搬",p:"bān",e:"Move (objects)"},
    {c:"我",p:"wǒ",e:"I/Me"},{c:"你",p:"nǐ",e:"You"},
    {c:"他",p:"tā",e:"He"},{c:"她",p:"tā",e:"She"},
    {c:"我们",p:"wǒ men",e:"We"},{c:"你们",p:"nǐ men",e:"You (plural)"},
    {c:"他们",p:"tā men",e:"They"},{c:"这",p:"zhè",e:"This"},
    {c:"那",p:"nà",e:"That"},{c:"什么",p:"shén me",e:"What"},
    {c:"哪里",p:"nǎ lǐ",e:"Where"},{c:"谁",p:"shuí",e:"Who"},
    {c:"怎么",p:"zěn me",e:"How"},{c:"为什么",p:"wèi shén me",e:"Why"},
    {c:"多少",p:"duō shǎo",e:"How many"},{c:"几",p:"jǐ",e:"How many (small)"},
    {c:"百",p:"bǎi",e:"Hundred"},{c:"千",p:"qiān",e:"Thousand"},
    {c:"万",p:"wàn",e:"Ten thousand"},{c:"零",p:"líng",e:"Zero"},
    {c:"中国",p:"zhōng guó",e:"China"},{c:"美国",p:"měi guó",e:"America"},
    {c:"日本",p:"rì běn",e:"Japan"},{c:"世界",p:"shì jiè",e:"World"},
    {c:"地球",p:"dì qiú",e:"Earth",i:"globe-showing-asia-australia"},
  ],
  7: [
    {c:"环境",p:"huán jìng",e:"Environment"},{c:"保护",p:"bǎo hù",e:"Protect"},
    {c:"动物",p:"dòng wù",e:"Animal"},{c:"植物",p:"zhí wù",e:"Plant"},
    {c:"科学",p:"kē xué",e:"Science"},{c:"数学",p:"shù xué",e:"Math"},
    {c:"历史",p:"lì shǐ",e:"History"},{c:"地理",p:"dì lǐ",e:"Geography"},
    {c:"语文",p:"yǔ wén",e:"Chinese (subject)"},{c:"英语",p:"yīng yǔ",e:"English"},
    {c:"体育",p:"tǐ yù",e:"PE"},{c:"美术",p:"měi shù",e:"Art"},
    {c:"已经",p:"yǐ jīng",e:"Already"},{c:"还",p:"hái",e:"Still"},
    {c:"才",p:"cái",e:"Only then"},{c:"就",p:"jiù",e:"Then"},
    {c:"虽然",p:"suī rán",e:"Although"},{c:"但是",p:"dàn shì",e:"But"},
    {c:"因为",p:"yīn wèi",e:"Because"},{c:"所以",p:"suǒ yǐ",e:"So"},
    {c:"如果",p:"rú guǒ",e:"If"},{c:"或者",p:"huò zhě",e:"Or"},
    {c:"而且",p:"ér qiě",e:"Moreover"},{c:"然后",p:"rán hòu",e:"Then"},
    {c:"以前",p:"yǐ qián",e:"Before"},{c:"以后",p:"yǐ hòu",e:"After"},
    {c:"经常",p:"jīng cháng",e:"Often"},{c:"有时候",p:"yǒu shí hou",e:"Sometimes"},
    {c:"马上",p:"mǎ shàng",e:"Immediately"},{c:"突然",p:"tū rán",e:"Suddenly"},
    {c:"特别",p:"tè bié",e:"Especially"},{c:"非常",p:"fēi cháng",e:"Very"},
    {c:"必须",p:"bì xū",e:"Must"},{c:"可能",p:"kě néng",e:"Maybe"},
    {c:"一定",p:"yí dìng",e:"Certainly"},{c:"重要",p:"zhòng yào",e:"Important"},
    {c:"安全",p:"ān quán",e:"Safe"},{c:"危险",p:"wēi xiǎn",e:"Dangerous"},
    {c:"健康",p:"jiàn kāng",e:"Healthy"},{c:"努力",p:"nǔ lì",e:"Hard-working"},
    {c:"成功",p:"chéng gōng",e:"Success"},{c:"失败",p:"shī bài",e:"Failure"},
    {c:"发现",p:"fā xiàn",e:"Discover"},{c:"解决",p:"jiě jué",e:"Solve"},
    {c:"相信",p:"xiāng xìn",e:"Believe"},{c:"同意",p:"tóng yì",e:"Agree"},
    {c:"决定",p:"jué dìng",e:"Decide"},{c:"准备",p:"zhǔn bèi",e:"Prepare"},
    {c:"计划",p:"jì huà",e:"Plan"},{c:"开始",p:"kāi shǐ",e:"Begin"},
    {c:"结束",p:"jié shù",e:"End"},{c:"继续",p:"jì xù",e:"Continue"},
    {c:"完成",p:"wán chéng",e:"Complete"},{c:"变化",p:"biàn huà",e:"Change"},
    {c:"发展",p:"fā zhǎn",e:"Develop"},{c:"提高",p:"tí gāo",e:"Improve"},
    {c:"增加",p:"zēng jiā",e:"Increase"},{c:"减少",p:"jiǎn shǎo",e:"Decrease"},
    {c:"参加",p:"cān jiā",e:"Participate"},{c:"比赛",p:"bǐ sài",e:"Competition"},
    {c:"练习",p:"liàn xí",e:"Practice"},{c:"表演",p:"biǎo yǎn",e:"Perform"},
    {c:"注意",p:"zhù yì",e:"Pay attention"},{c:"记住",p:"jì zhù",e:"Remember"},
    {c:"忘记",p:"wàng jì",e:"Forget"},{c:"理解",p:"lǐ jiě",e:"Understand"},
    {c:"翻译",p:"fān yì",e:"Translate"},{c:"解释",p:"jiě shì",e:"Explain"},
    {c:"讨论",p:"tǎo lùn",e:"Discuss"},{c:"介绍",p:"jiè shào",e:"Introduce"},
    {c:"通知",p:"tōng zhī",e:"Notify"},{c:"邀请",p:"yāo qǐng",e:"Invite"},
    {c:"拒绝",p:"jù jué",e:"Refuse"},{c:"接受",p:"jiē shòu",e:"Accept"},
    {c:"感谢",p:"gǎn xiè",e:"Thank"},{c:"道歉",p:"dào qiàn",e:"Apologize"},
    {c:"表示",p:"biǎo shì",e:"Express"},{c:"希望",p:"xī wàng",e:"Hope"},
    {c:"担心",p:"dān xīn",e:"Worry"},{c:"生活",p:"shēng huó",e:"Life"},
    {c:"经历",p:"jīng lì",e:"Experience"},{c:"回忆",p:"huí yì",e:"Memory"},
    {c:"故事",p:"gù shi",e:"Story"},{c:"新闻",p:"xīn wén",e:"News"},
    {c:"报纸",p:"bào zhǐ",e:"Newspaper"},{c:"杂志",p:"zá zhì",e:"Magazine"},
    {c:"节目",p:"jié mù",e:"Program/Show"},{c:"电影",p:"diàn yǐng",e:"Movie"},
    {c:"照片",p:"zhào piàn",e:"Photo"},{c:"照相机",p:"zhào xiàng jī",e:"Camera"},
    {c:"网络",p:"wǎng luò",e:"Internet"},{c:"信息",p:"xìn xī",e:"Information"},
    {c:"密码",p:"mì mǎ",e:"Password"},{c:"地址",p:"dì zhǐ",e:"Address"},
    {c:"号码",p:"hào mǎ",e:"Number"},{c:"护照",p:"hù zhào",e:"Passport"},
    {c:"签证",p:"qiān zhèng",e:"Visa"},{c:"行李",p:"xíng li",e:"Luggage"},
  ],
  8: [
    {c:"经济",p:"jīng jì",e:"Economy"},{c:"政治",p:"zhèng zhì",e:"Politics"},
    {c:"社会",p:"shè huì",e:"Society"},{c:"文化",p:"wén huà",e:"Culture"},
    {c:"技术",p:"jì shù",e:"Technology"},{c:"传统",p:"chuán tǒng",e:"Traditional"},
    {c:"现代",p:"xiàn dài",e:"Modern"},{c:"国际",p:"guó jì",e:"International"},
    {c:"交流",p:"jiāo liú",e:"Exchange"},{c:"合作",p:"hé zuò",e:"Cooperate"},
    {c:"竞争",p:"jìng zhēng",e:"Competition"},{c:"影响",p:"yǐng xiǎng",e:"Influence"},
    {c:"责任",p:"zé rèn",e:"Responsibility"},{c:"经验",p:"jīng yàn",e:"Experience"},
    {c:"机会",p:"jī huì",e:"Opportunity"},{c:"困难",p:"kùn nán",e:"Difficulty"},
    {c:"问题",p:"wèn tí",e:"Problem"},{c:"答案",p:"dá àn",e:"Answer"},
    {c:"方法",p:"fāng fǎ",e:"Method"},{c:"原因",p:"yuán yīn",e:"Reason"},
    {c:"结果",p:"jié guǒ",e:"Result"},{c:"关系",p:"guān xi",e:"Relationship"},
    {c:"情况",p:"qíng kuàng",e:"Situation"},{c:"条件",p:"tiáo jiàn",e:"Condition"},
    {c:"目标",p:"mù biāo",e:"Goal"},{c:"意见",p:"yì jiàn",e:"Opinion"},
    {c:"建议",p:"jiàn yì",e:"Suggestion"},{c:"态度",p:"tài du",e:"Attitude"},
    {c:"精神",p:"jīng shén",e:"Spirit"},{c:"感觉",p:"gǎn jué",e:"Feel"},
    {c:"思想",p:"sī xiǎng",e:"Thought"},{c:"梦想",p:"mèng xiǎng",e:"Dream"},
    {c:"幸福",p:"xìng fú",e:"Happiness"},{c:"自由",p:"zì yóu",e:"Freedom"},
    {c:"和平",p:"hé píng",e:"Peace",i:"peace-symbol"},
    {c:"尊重",p:"zūn zhòng",e:"Respect"},{c:"诚实",p:"chéng shí",e:"Honest"},
    {c:"勤劳",p:"qín láo",e:"Diligent"},{c:"耐心",p:"nài xīn",e:"Patient"},
    {c:"谦虚",p:"qiān xū",e:"Humble"},{c:"勇气",p:"yǒng qì",e:"Courage"},
    {c:"智慧",p:"zhì huì",e:"Wisdom"},{c:"知识",p:"zhī shi",e:"Knowledge"},
    {c:"教育",p:"jiào yù",e:"Education"},{c:"研究",p:"yán jiū",e:"Research"},
    {c:"实验",p:"shí yàn",e:"Experiment"},{c:"发明",p:"fā míng",e:"Invent"},
    {c:"创造",p:"chuàng zào",e:"Create"},{c:"设计",p:"shè jì",e:"Design"},
    {c:"管理",p:"guǎn lǐ",e:"Manage"},{c:"组织",p:"zǔ zhī",e:"Organize"},
    {c:"领导",p:"lǐng dǎo",e:"Lead"},{c:"团队",p:"tuán duì",e:"Team"},
    {c:"公司",p:"gōng sī",e:"Company"},{c:"工厂",p:"gōng chǎng",e:"Factory"},
    {c:"产品",p:"chǎn pǐn",e:"Product"},{c:"服务",p:"fú wù",e:"Service"},
    {c:"质量",p:"zhì liàng",e:"Quality"},{c:"价格",p:"jià gé",e:"Price"},
    {c:"广告",p:"guǎng gào",e:"Advertisement"},{c:"品牌",p:"pǐn pái",e:"Brand"},
    {c:"客户",p:"kè hù",e:"Customer"},{c:"合同",p:"hé tong",e:"Contract"},
    {c:"法律",p:"fǎ lǜ",e:"Law"},{c:"规则",p:"guī zé",e:"Rule"},
    {c:"权利",p:"quán lì",e:"Right (legal)"},{c:"义务",p:"yì wù",e:"Duty"},
    {c:"自然",p:"zì rán",e:"Nature"},{c:"空气",p:"kōng qì",e:"Air"},
    {c:"污染",p:"wū rǎn",e:"Pollution"},{c:"能源",p:"néng yuán",e:"Energy"},
    {c:"资源",p:"zī yuán",e:"Resource"},{c:"回收",p:"huí shōu",e:"Recycle"},
    {c:"节约",p:"jié yuē",e:"Save/Conserve"},{c:"太空",p:"tài kōng",e:"Space"},
    {c:"宇宙",p:"yǔ zhòu",e:"Universe"},{c:"星球",p:"xīng qiú",e:"Planet"},
    {c:"科技",p:"kē jì",e:"Tech"},{c:"人工智能",p:"rén gōng zhì néng",e:"AI"},
    {c:"机器人",p:"jī qì rén",e:"Robot"},{c:"程序",p:"chéng xù",e:"Program"},
    {c:"数据",p:"shù jù",e:"Data"},{c:"系统",p:"xì tǒng",e:"System"},
  ],
};

// Build flat lookup
const ALL_WORDS = {};
for (const level in WORD_BANK) {
  for (const w of WORD_BANK[level]) {
    ALL_WORDS[w.c] = w;
  }
}

// Map levels to age/maxLevel settings
const LEVEL_CAP = { "3-5": 3, "6-8": 5, "9-11": 7, "12+": 8 };
