const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const origin=process.env.BATTLE_ORIGIN||'http://127.0.0.1:8902',out=process.env.ARTIFACT_DIR||new URL('../design/acceptance/playtest-polish/',import.meta.url).pathname;mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),results=[];
for(const [width,height]of [[320,740],[844,390],[1024,768]]){
 const p=await browser.newPage({viewport:{width,height}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/creature-battle/?v=24');await p.locator('#play-ai').click();
 const input=p.getByLabel('Trainer name',{exact:true});assert.match(await input.inputValue(),/^Test Trainer/);
 const trainer=p.locator('.carousel-group:nth-child(2) .trainer-card').nth(1);await trainer.click();const original=await input.inputValue();assert.equal(await trainer.innerText(),original);
 await input.fill('  Captain Noodle  ');assert.equal(await trainer.innerText(),original);
 const cards=p.locator('.carousel-group:nth-child(2) .pick-card');for(let i=0;i<3;i++)await cards.nth(i).click();assert.equal(await p.locator('#team-done').isEnabled(),true);
 assert.equal(await p.locator('.selection small').count(),0);for(const credit of await cards.locator('.creature-creator').allTextContents())assert.match(credit,/^Made by Test Trainer/);
 // Battle nickname is separate from the original creator credit, and drafts follow portraits.
 await p.locator('.carousel-group:nth-child(2) .trainer-card').nth(2).click();assert.match(await input.inputValue(),/^Test Trainer/);await trainer.click();assert.equal(await input.inputValue(),original);await input.fill('Captain Noodle');
 for(const bad of ['Sh1t','I hate you','You are stupid','']){await input.fill(bad);assert.equal(await p.locator('#team-done').isEnabled(),false);assert.equal(await input.getAttribute('aria-invalid'),'true');assert.ok(await p.locator('#trainer-name-error').isVisible());assert.equal(await trainer.innerText(),original);}
 await p.screenshot({fullPage:true,path:`${out}/name-check-${width}.png`});await input.fill('Captain Noodle');assert.equal(await p.locator('#team-done').isEnabled(),true);assert.equal(await p.locator('#trainer-name-error').isVisible(),false);
 assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await input.isVisible());await p.screenshot({fullPage:true,path:`${out}/picker-${width}.png`});
 const href=await p.evaluate(async()=>{await document.querySelector('#game-home').click();return document.querySelector('#print-sheet').getAttribute('href');});assert.equal(href,'output/pdf/creature-sheet.pdf?v=24');await p.locator('#play-ai').click();await input.fill('Captain Noodle');for(let i=0;i<3;i++)await p.locator('.carousel-group:nth-child(2) .pick-card').nth(i).click();await p.locator('#team-done').click();if(width>height){await p.locator('#battle-text').click();await p.locator('[data-side="0"] [data-action="regular"]:enabled').waitFor();assert.match(await p.locator('#battle-text').innerText(),/Captain Noodle's turn/);}
 assert.deepEqual(errors,[]);results.push({width,height,creatorCredits:true,trainerNames:true,invalidNamesBlocked:true});await p.close();
}
// Same chosen name is retained for both players, with a number to distinguish turns.
const p=await browser.newPage({viewport:{width:844,height:390}});await p.goto(origin+'/creature-battle/?v=24');await p.locator('#play-friend').click();for(let side=0;side<2;side++){await p.locator('#trainer-name').fill('Moss');for(let i=0;i<3;i++)await p.locator('.carousel-group:nth-child(2) .pick-card').nth(i).click();await p.locator('#team-done').click();}await p.locator('#battle-text').click();await p.waitForTimeout(450);assert.match(await p.locator('#battle-text').innerText(),/Moss [12]'s turn/);await p.close();
await browser.close();writeFileSync(`${out}/results.json`,JSON.stringify(results,null,2));console.log('Trainer names, immutable creator credits, name checks, duplicate trainer names and sheet link pass at three sizes.');
