const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');import assert from 'node:assert/strict';import {mkdirSync} from 'node:fs';
const origin=process.env.BATTLE_ORIGIN||'http://127.0.0.1:8902',out=process.env.ARTIFACT_DIR||'/tmp/cb-playtest-browser';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || undefined,headless:true});
for(const [width,height]of [[667,375],[844,390],[1024,768]]){
 const p=await browser.newPage({viewport:{width,height}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/creature-battle/?debug=1');await p.waitForFunction(()=>window.__battleReady);
 await p.locator('#play-ai').click();await p.locator('#solo-opponent').click();await p.getByRole('option',{name:'Random Battle Bot',exact:true}).click();await p.locator('#opponent-next').click();const trainer=p.locator('.carousel-group:nth-child(2) .trainer-card').first();await trainer.click();await p.locator('.remove-creature').click();const original=await trainer.innerText();await p.locator('#trainer-name').fill('Xin');assert.equal(await trainer.innerText(),original);
 const cards=p.locator('.carousel-group:nth-child(2) .pick-card');assert.equal(await cards.locator('.creature-creator').count(),6);for(let i=0;i<3;i++)await cards.nth(i).click();assert.equal(await p.locator('.selection .creature-creator,.selection small').count(),0);const ids=await p.locator('.selection .team-creature-name').allTextContents();
 await p.screenshot({fullPage:true,path:`${out}/picker-${width}.png`});await p.locator('#team-done').click();await p.locator('[data-action]:enabled').first().waitFor();
 const opening=await p.evaluate(()=>{const s=__battleDebug.state();return s.rules.types[s.teams[0][0].type].strong.includes(s.teams[1][0].type);});assert.ok(opening);
 assert.ok(await p.locator('#quit-game').isVisible());await p.locator('#quit-game').click();assert.ok(await p.locator('#quit-dialog').isVisible());await p.locator('#keep-playing').click();assert.ok(await p.locator('#battle-text').isVisible());await p.locator('#game-home').click();assert.ok(await p.locator('#quit-dialog').isVisible());await p.keyboard.press('Escape');assert.ok(await p.locator('#battle-text').isVisible());
 assert.ok(await p.locator('.category').evaluateAll(es=>es.every(e=>{const r=e.getBoundingClientRect();return getComputedStyle(e).whiteSpace==='nowrap'&&r.width<=e.parentElement.clientWidth;})));
 await p.screenshot({path:`${out}/arena-${width}.png`});
 // Isolated view checks for medium/low HP, merged narration and the full replacement tray.
 await p.evaluate(async()=>{const {battleView}=await import(`/creature-battle/releases/v46/src/ui/battle.js?v=${GAME_VERSION}`);const initial=__battleDebug.state();initial.teams[0][initial.active[0]].hp=Math.floor(initial.teams[0][initial.active[0]].maxHp*.4);initial.teams[1][initial.active[1]].hp=1;const state=structuredClone(initial);window.polishView=battleView({app:document.querySelector('#app'),initial,trainers:[{nickname:'Xin'},{nickname:'Bot'}],humanSides:[0,1],imageSrc:()=>'/creature-battle/tests/fixtures/placeholder.svg',portraitSrc:()=>'/creature-battle/tests/fixtures/portrait.svg',getState:()=>state,onAction:()=>{},onReplacement:()=>{},onDrain:()=>{},twoTap:()=>false});state.teams[0][state.active[0]].hp=0;state.needReplacement=0;window.polishState=state;});
 assert.equal(await p.locator('.hp-medium').count(),1);assert.equal(await p.locator('.hp-low').count(),1);assert.equal(await p.locator('.hp-low .hp-fill').evaluate(e=>getComputedStyle(e).animationName),'hp-warning');
 await p.evaluate(()=>{return polishView.animate([{t:'use',side:1,name:'Energy Burst',moveId:'blast',ppAfter:polishState.teams[1][0].pp},{t:'hit',side:1,target:0,amount:51,absorbed:0,crit:false,eff:null,hpAfter:0},{t:'faint',side:0},{t:'needReplace',side:0}]);});await p.waitForTimeout(450);
 const rows=await p.locator('.message-line').allTextContents();assert.ok(rows.some(t=>/used Energy Burst! It dealt 51 damage/.test(t)));assert.ok(rows.some(t=>/fainted! Xin, choose your next creature/.test(t)));
 assert.equal(await p.locator('.replacement-tray .bench-card').count(),3);assert.equal(await p.locator('.replacement-tray .bench-fainted:disabled').count(),1);assert.equal(await p.locator('.replacement-tray .bench-card:enabled').count(),2);
 assert.ok(await p.locator('.replacement-tray').evaluate(e=>e.scrollHeight<=e.clientHeight+1));assert.ok(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1));await p.screenshot({path:`${out}/replacement-${width}.png`});assert.deepEqual(errors,[]);
 await p.locator('#game-home').click();await p.locator('#confirm-quit').click();assert.ok(await p.locator('#play-ai').isVisible());assert.equal(await p.locator('#quit-game').isVisible(),false);await p.close();
}
await browser.close();console.log('Playtest polish: source portrait labels, creature credits, weak Easy bot opener, quit confirmation, one-line controls, HP colours, merged narration and full replacement tray pass at three sizes.');
